//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AcmeAuthorization = newAcmeAuthorizationTable("public", "acme_authorization", "")

type acmeAuthorizationTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	OrganizationID  postgres.ColumnString
	AcmeOrderID     postgres.ColumnString
	IdentifierType  postgres.ColumnString
	IdentifierValue postgres.ColumnString
	Status          postgres.ColumnString
	ExpiresAt       postgres.ColumnTimestamp
	ValidatedAt     postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AcmeAuthorizationTable struct {
	acmeAuthorizationTable

	EXCLUDED acmeAuthorizationTable
}

// AS creates new AcmeAuthorizationTable with assigned alias
func (a AcmeAuthorizationTable) AS(alias string) *AcmeAuthorizationTable {
	return newAcmeAuthorizationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AcmeAuthorizationTable with assigned schema name
func (a AcmeAuthorizationTable) FromSchema(schemaName string) *AcmeAuthorizationTable {
	return newAcmeAuthorizationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AcmeAuthorizationTable with assigned table prefix
func (a AcmeAuthorizationTable) WithPrefix(prefix string) *AcmeAuthorizationTable {
	return newAcmeAuthorizationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AcmeAuthorizationTable with assigned table suffix
func (a AcmeAuthorizationTable) WithSuffix(suffix string) *AcmeAuthorizationTable {
	return newAcmeAuthorizationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAcmeAuthorizationTable(schemaName, tableName, alias string) *AcmeAuthorizationTable {
	return &AcmeAuthorizationTable{
		acmeAuthorizationTable: newAcmeAuthorizationTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newAcmeAuthorizationTableImpl("", "excluded", ""),
	}
}

func newAcmeAuthorizationTableImpl(schemaName, tableName, alias string) acmeAuthorizationTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		OrganizationIDColumn  = postgres.StringColumn("organization_id")
		AcmeOrderIDColumn     = postgres.StringColumn("acme_order_id")
		IdentifierTypeColumn  = postgres.StringColumn("identifier_type")
		IdentifierValueColumn = postgres.StringColumn("identifier_value")
		StatusColumn          = postgres.StringColumn("status")
		ExpiresAtColumn       = postgres.TimestampColumn("expires_at")
		ValidatedAtColumn     = postgres.TimestampColumn("validated_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		allColumns            = postgres.ColumnList{IDColumn, OrganizationIDColumn, AcmeOrderIDColumn, IdentifierTypeColumn, IdentifierValueColumn, StatusColumn, ExpiresAtColumn, ValidatedAtColumn, CreatedAtColumn}
		mutableColumns        = postgres.ColumnList{OrganizationIDColumn, AcmeOrderIDColumn, IdentifierTypeColumn, IdentifierValueColumn, StatusColumn, ExpiresAtColumn, ValidatedAtColumn, CreatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return acmeAuthorizationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		OrganizationID:  OrganizationIDColumn,
		AcmeOrderID:     AcmeOrderIDColumn,
		IdentifierType:  IdentifierTypeColumn,
		IdentifierValue: IdentifierValueColumn,
		Status:          StatusColumn,
		ExpiresAt:       ExpiresAtColumn,
		ValidatedAt:     ValidatedAtColumn,
		CreatedAt:       CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
