//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AcmeOrder = newAcmeOrderTable("public", "acme_order", "")

type acmeOrderTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OrganizationID postgres.ColumnString
	AcmeEndpointID postgres.ColumnString
	AcmeAccountID  postgres.ColumnString
	Status         postgres.ColumnString
	ExpiresAt      postgres.ColumnTimestamp
	NotBefore      postgres.ColumnTimestamp
	NotAfter       postgres.ColumnTimestamp
	CertificateID  postgres.ColumnString
	ErrorType      postgres.ColumnString
	ErrorDetail    postgres.ColumnString
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AcmeOrderTable struct {
	acmeOrderTable

	EXCLUDED acmeOrderTable
}

// AS creates new AcmeOrderTable with assigned alias
func (a AcmeOrderTable) AS(alias string) *AcmeOrderTable {
	return newAcmeOrderTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AcmeOrderTable with assigned schema name
func (a AcmeOrderTable) FromSchema(schemaName string) *AcmeOrderTable {
	return newAcmeOrderTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AcmeOrderTable with assigned table prefix
func (a AcmeOrderTable) WithPrefix(prefix string) *AcmeOrderTable {
	return newAcmeOrderTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AcmeOrderTable with assigned table suffix
func (a AcmeOrderTable) WithSuffix(suffix string) *AcmeOrderTable {
	return newAcmeOrderTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAcmeOrderTable(schemaName, tableName, alias string) *AcmeOrderTable {
	return &AcmeOrderTable{
		acmeOrderTable: newAcmeOrderTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newAcmeOrderTableImpl("", "excluded", ""),
	}
}

func newAcmeOrderTableImpl(schemaName, tableName, alias string) acmeOrderTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		AcmeEndpointIDColumn = postgres.StringColumn("acme_endpoint_id")
		AcmeAccountIDColumn  = postgres.StringColumn("acme_account_id")
		StatusColumn         = postgres.StringColumn("status")
		ExpiresAtColumn      = postgres.TimestampColumn("expires_at")
		NotBeforeColumn      = postgres.TimestampColumn("not_before")
		NotAfterColumn       = postgres.TimestampColumn("not_after")
		CertificateIDColumn  = postgres.StringColumn("certificate_id")
		ErrorTypeColumn      = postgres.StringColumn("error_type")
		ErrorDetailColumn    = postgres.StringColumn("error_detail")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{IDColumn, OrganizationIDColumn, AcmeEndpointIDColumn, AcmeAccountIDColumn, StatusColumn, ExpiresAtColumn, NotBeforeColumn, NotAfterColumn, CertificateIDColumn, ErrorTypeColumn, ErrorDetailColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{OrganizationIDColumn, AcmeEndpointIDColumn, AcmeAccountIDColumn, StatusColumn, ExpiresAtColumn, NotBeforeColumn, NotAfterColumn, CertificateIDColumn, ErrorTypeColumn, ErrorDetailColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, StatusColumn, ErrorTypeColumn, ErrorDetailColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return acmeOrderTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OrganizationID: OrganizationIDColumn,
		AcmeEndpointID: AcmeEndpointIDColumn,
		AcmeAccountID:  AcmeAccountIDColumn,
		Status:         StatusColumn,
		ExpiresAt:      ExpiresAtColumn,
		NotBefore:      NotBeforeColumn,
		NotAfter:       NotAfterColumn,
		CertificateID:  CertificateIDColumn,
		ErrorType:      ErrorTypeColumn,
		ErrorDetail:    ErrorDetailColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
