//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AcmeEabCredential = newAcmeEabCredentialTable("public", "acme_eab_credential", "")

type acmeEabCredentialTable struct {
	postgres.Table

	// Columns
	ID               postgres.ColumnString
	OrganizationID   postgres.ColumnString
	AcmeEndpointID   postgres.ColumnString
	Label            postgres.ColumnString
	Kid              postgres.ColumnString
	MacKeyCiphertext postgres.ColumnBytea
	IdentifierPin    postgres.ColumnString
	SingleUse        postgres.ColumnBool
	ExpiresAt        postgres.ColumnTimestamp
	UsedAt           postgres.ColumnTimestamp
	RevokedAt        postgres.ColumnTimestamp
	CreatedAt        postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AcmeEabCredentialTable struct {
	acmeEabCredentialTable

	EXCLUDED acmeEabCredentialTable
}

// AS creates new AcmeEabCredentialTable with assigned alias
func (a AcmeEabCredentialTable) AS(alias string) *AcmeEabCredentialTable {
	return newAcmeEabCredentialTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AcmeEabCredentialTable with assigned schema name
func (a AcmeEabCredentialTable) FromSchema(schemaName string) *AcmeEabCredentialTable {
	return newAcmeEabCredentialTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AcmeEabCredentialTable with assigned table prefix
func (a AcmeEabCredentialTable) WithPrefix(prefix string) *AcmeEabCredentialTable {
	return newAcmeEabCredentialTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AcmeEabCredentialTable with assigned table suffix
func (a AcmeEabCredentialTable) WithSuffix(suffix string) *AcmeEabCredentialTable {
	return newAcmeEabCredentialTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAcmeEabCredentialTable(schemaName, tableName, alias string) *AcmeEabCredentialTable {
	return &AcmeEabCredentialTable{
		acmeEabCredentialTable: newAcmeEabCredentialTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newAcmeEabCredentialTableImpl("", "excluded", ""),
	}
}

func newAcmeEabCredentialTableImpl(schemaName, tableName, alias string) acmeEabCredentialTable {
	var (
		IDColumn               = postgres.StringColumn("id")
		OrganizationIDColumn   = postgres.StringColumn("organization_id")
		AcmeEndpointIDColumn   = postgres.StringColumn("acme_endpoint_id")
		LabelColumn            = postgres.StringColumn("label")
		KidColumn              = postgres.StringColumn("kid")
		MacKeyCiphertextColumn = postgres.ByteaColumn("mac_key_ciphertext")
		IdentifierPinColumn    = postgres.StringColumn("identifier_pin")
		SingleUseColumn        = postgres.BoolColumn("single_use")
		ExpiresAtColumn        = postgres.TimestampColumn("expires_at")
		UsedAtColumn           = postgres.TimestampColumn("used_at")
		RevokedAtColumn        = postgres.TimestampColumn("revoked_at")
		CreatedAtColumn        = postgres.TimestampColumn("created_at")
		allColumns             = postgres.ColumnList{IDColumn, OrganizationIDColumn, AcmeEndpointIDColumn, LabelColumn, KidColumn, MacKeyCiphertextColumn, IdentifierPinColumn, SingleUseColumn, ExpiresAtColumn, UsedAtColumn, RevokedAtColumn, CreatedAtColumn}
		mutableColumns         = postgres.ColumnList{OrganizationIDColumn, AcmeEndpointIDColumn, LabelColumn, KidColumn, MacKeyCiphertextColumn, IdentifierPinColumn, SingleUseColumn, ExpiresAtColumn, UsedAtColumn, RevokedAtColumn, CreatedAtColumn}
		defaultColumns         = postgres.ColumnList{IDColumn, LabelColumn, IdentifierPinColumn, SingleUseColumn, CreatedAtColumn}
	)

	return acmeEabCredentialTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:               IDColumn,
		OrganizationID:   OrganizationIDColumn,
		AcmeEndpointID:   AcmeEndpointIDColumn,
		Label:            LabelColumn,
		Kid:              KidColumn,
		MacKeyCiphertext: MacKeyCiphertextColumn,
		IdentifierPin:    IdentifierPinColumn,
		SingleUse:        SingleUseColumn,
		ExpiresAt:        ExpiresAtColumn,
		UsedAt:           UsedAtColumn,
		RevokedAt:        RevokedAtColumn,
		CreatedAt:        CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
