//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AcmeEndpoint = newAcmeEndpointTable("public", "acme_endpoint", "")

type acmeEndpointTable struct {
	postgres.Table

	// Columns
	ID                     postgres.ColumnString
	OrganizationID         postgres.ColumnString
	CertificateAuthorityID postgres.ColumnString
	Name                   postgres.ColumnString
	Enabled                postgres.ColumnBool
	ValidityDays           postgres.ColumnInteger
	AllowedEkus            postgres.ColumnString
	SubjectPattern         postgres.ColumnString
	SanPattern             postgres.ColumnString
	CreatedAt              postgres.ColumnTimestamp
	UpdatedAt              postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AcmeEndpointTable struct {
	acmeEndpointTable

	EXCLUDED acmeEndpointTable
}

// AS creates new AcmeEndpointTable with assigned alias
func (a AcmeEndpointTable) AS(alias string) *AcmeEndpointTable {
	return newAcmeEndpointTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AcmeEndpointTable with assigned schema name
func (a AcmeEndpointTable) FromSchema(schemaName string) *AcmeEndpointTable {
	return newAcmeEndpointTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AcmeEndpointTable with assigned table prefix
func (a AcmeEndpointTable) WithPrefix(prefix string) *AcmeEndpointTable {
	return newAcmeEndpointTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AcmeEndpointTable with assigned table suffix
func (a AcmeEndpointTable) WithSuffix(suffix string) *AcmeEndpointTable {
	return newAcmeEndpointTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAcmeEndpointTable(schemaName, tableName, alias string) *AcmeEndpointTable {
	return &AcmeEndpointTable{
		acmeEndpointTable: newAcmeEndpointTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newAcmeEndpointTableImpl("", "excluded", ""),
	}
}

func newAcmeEndpointTableImpl(schemaName, tableName, alias string) acmeEndpointTable {
	var (
		IDColumn                     = postgres.StringColumn("id")
		OrganizationIDColumn         = postgres.StringColumn("organization_id")
		CertificateAuthorityIDColumn = postgres.StringColumn("certificate_authority_id")
		NameColumn                   = postgres.StringColumn("name")
		EnabledColumn                = postgres.BoolColumn("enabled")
		ValidityDaysColumn           = postgres.IntegerColumn("validity_days")
		AllowedEkusColumn            = postgres.StringColumn("allowed_ekus")
		SubjectPatternColumn         = postgres.StringColumn("subject_pattern")
		SanPatternColumn             = postgres.StringColumn("san_pattern")
		CreatedAtColumn              = postgres.TimestampColumn("created_at")
		UpdatedAtColumn              = postgres.TimestampColumn("updated_at")
		allColumns                   = postgres.ColumnList{IDColumn, OrganizationIDColumn, CertificateAuthorityIDColumn, NameColumn, EnabledColumn, ValidityDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns               = postgres.ColumnList{OrganizationIDColumn, CertificateAuthorityIDColumn, NameColumn, EnabledColumn, ValidityDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns               = postgres.ColumnList{IDColumn, EnabledColumn, ValidityDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return acmeEndpointTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		OrganizationID:         OrganizationIDColumn,
		CertificateAuthorityID: CertificateAuthorityIDColumn,
		Name:                   NameColumn,
		Enabled:                EnabledColumn,
		ValidityDays:           ValidityDaysColumn,
		AllowedEkus:            AllowedEkusColumn,
		SubjectPattern:         SubjectPatternColumn,
		SanPattern:             SanPatternColumn,
		CreatedAt:              CreatedAtColumn,
		UpdatedAt:              UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
