//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AcmeAccount = newAcmeAccountTable("public", "acme_account", "")

type acmeAccountTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	OrganizationID  postgres.ColumnString
	AcmeEndpointID  postgres.ColumnString
	JwkThumbprint   postgres.ColumnString
	JwkJSON         postgres.ColumnString
	Status          postgres.ColumnString
	Contact         postgres.ColumnString
	EabCredentialID postgres.ColumnString
	IdentifierPin   postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	UpdatedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AcmeAccountTable struct {
	acmeAccountTable

	EXCLUDED acmeAccountTable
}

// AS creates new AcmeAccountTable with assigned alias
func (a AcmeAccountTable) AS(alias string) *AcmeAccountTable {
	return newAcmeAccountTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AcmeAccountTable with assigned schema name
func (a AcmeAccountTable) FromSchema(schemaName string) *AcmeAccountTable {
	return newAcmeAccountTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AcmeAccountTable with assigned table prefix
func (a AcmeAccountTable) WithPrefix(prefix string) *AcmeAccountTable {
	return newAcmeAccountTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AcmeAccountTable with assigned table suffix
func (a AcmeAccountTable) WithSuffix(suffix string) *AcmeAccountTable {
	return newAcmeAccountTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAcmeAccountTable(schemaName, tableName, alias string) *AcmeAccountTable {
	return &AcmeAccountTable{
		acmeAccountTable: newAcmeAccountTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newAcmeAccountTableImpl("", "excluded", ""),
	}
}

func newAcmeAccountTableImpl(schemaName, tableName, alias string) acmeAccountTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		OrganizationIDColumn  = postgres.StringColumn("organization_id")
		AcmeEndpointIDColumn  = postgres.StringColumn("acme_endpoint_id")
		JwkThumbprintColumn   = postgres.StringColumn("jwk_thumbprint")
		JwkJSONColumn         = postgres.StringColumn("jwk_json")
		StatusColumn          = postgres.StringColumn("status")
		ContactColumn         = postgres.StringColumn("contact")
		EabCredentialIDColumn = postgres.StringColumn("eab_credential_id")
		IdentifierPinColumn   = postgres.StringColumn("identifier_pin")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		UpdatedAtColumn       = postgres.TimestampColumn("updated_at")
		allColumns            = postgres.ColumnList{IDColumn, OrganizationIDColumn, AcmeEndpointIDColumn, JwkThumbprintColumn, JwkJSONColumn, StatusColumn, ContactColumn, EabCredentialIDColumn, IdentifierPinColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns        = postgres.ColumnList{OrganizationIDColumn, AcmeEndpointIDColumn, JwkThumbprintColumn, JwkJSONColumn, StatusColumn, ContactColumn, EabCredentialIDColumn, IdentifierPinColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, StatusColumn, ContactColumn, IdentifierPinColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return acmeAccountTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		OrganizationID:  OrganizationIDColumn,
		AcmeEndpointID:  AcmeEndpointIDColumn,
		JwkThumbprint:   JwkThumbprintColumn,
		JwkJSON:         JwkJSONColumn,
		Status:          StatusColumn,
		Contact:         ContactColumn,
		EabCredentialID: EabCredentialIDColumn,
		IdentifierPin:   IdentifierPinColumn,
		CreatedAt:       CreatedAtColumn,
		UpdatedAt:       UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
