//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AcmeNonce = newAcmeNonceTable("public", "acme_nonce", "")

type acmeNonceTable struct {
	postgres.Table

	// Columns
	Value          postgres.ColumnBytea
	OrganizationID postgres.ColumnString
	AcmeEndpointID postgres.ColumnString
	IssuedAt       postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AcmeNonceTable struct {
	acmeNonceTable

	EXCLUDED acmeNonceTable
}

// AS creates new AcmeNonceTable with assigned alias
func (a AcmeNonceTable) AS(alias string) *AcmeNonceTable {
	return newAcmeNonceTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AcmeNonceTable with assigned schema name
func (a AcmeNonceTable) FromSchema(schemaName string) *AcmeNonceTable {
	return newAcmeNonceTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AcmeNonceTable with assigned table prefix
func (a AcmeNonceTable) WithPrefix(prefix string) *AcmeNonceTable {
	return newAcmeNonceTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AcmeNonceTable with assigned table suffix
func (a AcmeNonceTable) WithSuffix(suffix string) *AcmeNonceTable {
	return newAcmeNonceTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAcmeNonceTable(schemaName, tableName, alias string) *AcmeNonceTable {
	return &AcmeNonceTable{
		acmeNonceTable: newAcmeNonceTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newAcmeNonceTableImpl("", "excluded", ""),
	}
}

func newAcmeNonceTableImpl(schemaName, tableName, alias string) acmeNonceTable {
	var (
		ValueColumn          = postgres.ByteaColumn("value")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		AcmeEndpointIDColumn = postgres.StringColumn("acme_endpoint_id")
		IssuedAtColumn       = postgres.TimestampColumn("issued_at")
		allColumns           = postgres.ColumnList{ValueColumn, OrganizationIDColumn, AcmeEndpointIDColumn, IssuedAtColumn}
		mutableColumns       = postgres.ColumnList{OrganizationIDColumn, AcmeEndpointIDColumn, IssuedAtColumn}
		defaultColumns       = postgres.ColumnList{IssuedAtColumn}
	)

	return acmeNonceTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Value:          ValueColumn,
		OrganizationID: OrganizationIDColumn,
		AcmeEndpointID: AcmeEndpointIDColumn,
		IssuedAt:       IssuedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
