//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AcmeChallenge = newAcmeChallengeTable("public", "acme_challenge", "")

type acmeChallengeTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	OrganizationID      postgres.ColumnString
	AcmeAuthorizationID postgres.ColumnString
	Type                postgres.ColumnString
	Token               postgres.ColumnString
	Status              postgres.ColumnString
	ValidatedAt         postgres.ColumnTimestamp
	CreatedAt           postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AcmeChallengeTable struct {
	acmeChallengeTable

	EXCLUDED acmeChallengeTable
}

// AS creates new AcmeChallengeTable with assigned alias
func (a AcmeChallengeTable) AS(alias string) *AcmeChallengeTable {
	return newAcmeChallengeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AcmeChallengeTable with assigned schema name
func (a AcmeChallengeTable) FromSchema(schemaName string) *AcmeChallengeTable {
	return newAcmeChallengeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AcmeChallengeTable with assigned table prefix
func (a AcmeChallengeTable) WithPrefix(prefix string) *AcmeChallengeTable {
	return newAcmeChallengeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AcmeChallengeTable with assigned table suffix
func (a AcmeChallengeTable) WithSuffix(suffix string) *AcmeChallengeTable {
	return newAcmeChallengeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAcmeChallengeTable(schemaName, tableName, alias string) *AcmeChallengeTable {
	return &AcmeChallengeTable{
		acmeChallengeTable: newAcmeChallengeTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newAcmeChallengeTableImpl("", "excluded", ""),
	}
}

func newAcmeChallengeTableImpl(schemaName, tableName, alias string) acmeChallengeTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		OrganizationIDColumn      = postgres.StringColumn("organization_id")
		AcmeAuthorizationIDColumn = postgres.StringColumn("acme_authorization_id")
		TypeColumn                = postgres.StringColumn("type")
		TokenColumn               = postgres.StringColumn("token")
		StatusColumn              = postgres.StringColumn("status")
		ValidatedAtColumn         = postgres.TimestampColumn("validated_at")
		CreatedAtColumn           = postgres.TimestampColumn("created_at")
		allColumns                = postgres.ColumnList{IDColumn, OrganizationIDColumn, AcmeAuthorizationIDColumn, TypeColumn, TokenColumn, StatusColumn, ValidatedAtColumn, CreatedAtColumn}
		mutableColumns            = postgres.ColumnList{OrganizationIDColumn, AcmeAuthorizationIDColumn, TypeColumn, TokenColumn, StatusColumn, ValidatedAtColumn, CreatedAtColumn}
		defaultColumns            = postgres.ColumnList{IDColumn, StatusColumn, CreatedAtColumn}
	)

	return acmeChallengeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		OrganizationID:      OrganizationIDColumn,
		AcmeAuthorizationID: AcmeAuthorizationIDColumn,
		Type:                TypeColumn,
		Token:               TokenColumn,
		Status:              StatusColumn,
		ValidatedAt:         ValidatedAtColumn,
		CreatedAt:           CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
