//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var AuditEvent = newAuditEventTable("public", "audit_event", "")

type auditEventTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OrganizationID postgres.ColumnString
	ActorUserID    postgres.ColumnString
	ActorEmail     postgres.ColumnString
	Action         postgres.ColumnString
	Target         postgres.ColumnString
	Detail         postgres.ColumnString
	CreatedAt      postgres.ColumnTimestampz
	ActorIP        postgres.ColumnString
	ActorUserAgent postgres.ColumnString
	ActorSessionID postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type AuditEventTable struct {
	auditEventTable

	EXCLUDED auditEventTable
}

// AS creates new AuditEventTable with assigned alias
func (a AuditEventTable) AS(alias string) *AuditEventTable {
	return newAuditEventTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuditEventTable with assigned schema name
func (a AuditEventTable) FromSchema(schemaName string) *AuditEventTable {
	return newAuditEventTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuditEventTable with assigned table prefix
func (a AuditEventTable) WithPrefix(prefix string) *AuditEventTable {
	return newAuditEventTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuditEventTable with assigned table suffix
func (a AuditEventTable) WithSuffix(suffix string) *AuditEventTable {
	return newAuditEventTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuditEventTable(schemaName, tableName, alias string) *AuditEventTable {
	return &AuditEventTable{
		auditEventTable: newAuditEventTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newAuditEventTableImpl("", "excluded", ""),
	}
}

func newAuditEventTableImpl(schemaName, tableName, alias string) auditEventTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		ActorUserIDColumn    = postgres.StringColumn("actor_user_id")
		ActorEmailColumn     = postgres.StringColumn("actor_email")
		ActionColumn         = postgres.StringColumn("action")
		TargetColumn         = postgres.StringColumn("target")
		DetailColumn         = postgres.StringColumn("detail")
		CreatedAtColumn      = postgres.TimestampzColumn("created_at")
		ActorIPColumn        = postgres.StringColumn("actor_ip")
		ActorUserAgentColumn = postgres.StringColumn("actor_user_agent")
		ActorSessionIDColumn = postgres.StringColumn("actor_session_id")
		allColumns           = postgres.ColumnList{IDColumn, OrganizationIDColumn, ActorUserIDColumn, ActorEmailColumn, ActionColumn, TargetColumn, DetailColumn, CreatedAtColumn, ActorIPColumn, ActorUserAgentColumn, ActorSessionIDColumn}
		mutableColumns       = postgres.ColumnList{OrganizationIDColumn, ActorUserIDColumn, ActorEmailColumn, ActionColumn, TargetColumn, DetailColumn, CreatedAtColumn, ActorIPColumn, ActorUserAgentColumn, ActorSessionIDColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, ActorEmailColumn, TargetColumn, DetailColumn, CreatedAtColumn, ActorIPColumn, ActorUserAgentColumn, ActorSessionIDColumn}
	)

	return auditEventTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OrganizationID: OrganizationIDColumn,
		ActorUserID:    ActorUserIDColumn,
		ActorEmail:     ActorEmailColumn,
		Action:         ActionColumn,
		Target:         TargetColumn,
		Detail:         DetailColumn,
		CreatedAt:      CreatedAtColumn,
		ActorIP:        ActorIPColumn,
		ActorUserAgent: ActorUserAgentColumn,
		ActorSessionID: ActorSessionIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
