//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CaImportJob = newCaImportJobTable("public", "ca_import_job", "")

type caImportJobTable struct {
	postgres.Table

	// Columns
	ID                     postgres.ColumnString
	OrganizationID         postgres.ColumnString
	CreatedBy              postgres.ColumnString
	CaName                 postgres.ColumnString
	CaType                 postgres.ColumnString
	Algorithm              postgres.ColumnString
	CertificatePem         postgres.ColumnString
	ChainPem               postgres.ColumnString
	KmsImportJob           postgres.ColumnString
	KmsCryptoKey           postgres.ColumnString
	KmsKeyVersion          postgres.ColumnString
	WrappingMethod         postgres.ColumnString
	WrappingPublicKeyPem   postgres.ColumnString
	State                  postgres.ColumnString
	FailureReason          postgres.ColumnString
	CertificateAuthorityID postgres.ColumnString
	ExpiresAt              postgres.ColumnTimestamp
	CreatedAt              postgres.ColumnTimestamp
	CancelledBy            postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CaImportJobTable struct {
	caImportJobTable

	EXCLUDED caImportJobTable
}

// AS creates new CaImportJobTable with assigned alias
func (a CaImportJobTable) AS(alias string) *CaImportJobTable {
	return newCaImportJobTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CaImportJobTable with assigned schema name
func (a CaImportJobTable) FromSchema(schemaName string) *CaImportJobTable {
	return newCaImportJobTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CaImportJobTable with assigned table prefix
func (a CaImportJobTable) WithPrefix(prefix string) *CaImportJobTable {
	return newCaImportJobTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CaImportJobTable with assigned table suffix
func (a CaImportJobTable) WithSuffix(suffix string) *CaImportJobTable {
	return newCaImportJobTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCaImportJobTable(schemaName, tableName, alias string) *CaImportJobTable {
	return &CaImportJobTable{
		caImportJobTable: newCaImportJobTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newCaImportJobTableImpl("", "excluded", ""),
	}
}

func newCaImportJobTableImpl(schemaName, tableName, alias string) caImportJobTable {
	var (
		IDColumn                     = postgres.StringColumn("id")
		OrganizationIDColumn         = postgres.StringColumn("organization_id")
		CreatedByColumn              = postgres.StringColumn("created_by")
		CaNameColumn                 = postgres.StringColumn("ca_name")
		CaTypeColumn                 = postgres.StringColumn("ca_type")
		AlgorithmColumn              = postgres.StringColumn("algorithm")
		CertificatePemColumn         = postgres.StringColumn("certificate_pem")
		ChainPemColumn               = postgres.StringColumn("chain_pem")
		KmsImportJobColumn           = postgres.StringColumn("kms_import_job")
		KmsCryptoKeyColumn           = postgres.StringColumn("kms_crypto_key")
		KmsKeyVersionColumn          = postgres.StringColumn("kms_key_version")
		WrappingMethodColumn         = postgres.StringColumn("wrapping_method")
		WrappingPublicKeyPemColumn   = postgres.StringColumn("wrapping_public_key_pem")
		StateColumn                  = postgres.StringColumn("state")
		FailureReasonColumn          = postgres.StringColumn("failure_reason")
		CertificateAuthorityIDColumn = postgres.StringColumn("certificate_authority_id")
		ExpiresAtColumn              = postgres.TimestampColumn("expires_at")
		CreatedAtColumn              = postgres.TimestampColumn("created_at")
		CancelledByColumn            = postgres.StringColumn("cancelled_by")
		allColumns                   = postgres.ColumnList{IDColumn, OrganizationIDColumn, CreatedByColumn, CaNameColumn, CaTypeColumn, AlgorithmColumn, CertificatePemColumn, ChainPemColumn, KmsImportJobColumn, KmsCryptoKeyColumn, KmsKeyVersionColumn, WrappingMethodColumn, WrappingPublicKeyPemColumn, StateColumn, FailureReasonColumn, CertificateAuthorityIDColumn, ExpiresAtColumn, CreatedAtColumn, CancelledByColumn}
		mutableColumns               = postgres.ColumnList{OrganizationIDColumn, CreatedByColumn, CaNameColumn, CaTypeColumn, AlgorithmColumn, CertificatePemColumn, ChainPemColumn, KmsImportJobColumn, KmsCryptoKeyColumn, KmsKeyVersionColumn, WrappingMethodColumn, WrappingPublicKeyPemColumn, StateColumn, FailureReasonColumn, CertificateAuthorityIDColumn, ExpiresAtColumn, CreatedAtColumn, CancelledByColumn}
		defaultColumns               = postgres.ColumnList{IDColumn, ChainPemColumn, KmsKeyVersionColumn, WrappingMethodColumn, WrappingPublicKeyPemColumn, StateColumn, FailureReasonColumn, CreatedAtColumn}
	)

	return caImportJobTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		OrganizationID:         OrganizationIDColumn,
		CreatedBy:              CreatedByColumn,
		CaName:                 CaNameColumn,
		CaType:                 CaTypeColumn,
		Algorithm:              AlgorithmColumn,
		CertificatePem:         CertificatePemColumn,
		ChainPem:               ChainPemColumn,
		KmsImportJob:           KmsImportJobColumn,
		KmsCryptoKey:           KmsCryptoKeyColumn,
		KmsKeyVersion:          KmsKeyVersionColumn,
		WrappingMethod:         WrappingMethodColumn,
		WrappingPublicKeyPem:   WrappingPublicKeyPemColumn,
		State:                  StateColumn,
		FailureReason:          FailureReasonColumn,
		CertificateAuthorityID: CertificateAuthorityIDColumn,
		ExpiresAt:              ExpiresAtColumn,
		CreatedAt:              CreatedAtColumn,
		CancelledBy:            CancelledByColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
