//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CertificateAuthority = newCertificateAuthorityTable("public", "certificate_authority", "")

type certificateAuthorityTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OrganizationID postgres.ColumnString
	ParentID       postgres.ColumnString
	Name           postgres.ColumnString
	Type           postgres.ColumnString
	Status         postgres.ColumnString
	Subject        postgres.ColumnString
	Algorithm      postgres.ColumnString
	KmsKeyVersion  postgres.ColumnString
	CertificatePem postgres.ColumnString
	ChainPem       postgres.ColumnString
	ExportPosture  postgres.ColumnString
	NotBefore      postgres.ColumnTimestamp
	NotAfter       postgres.ColumnTimestamp
	IssuedCount    postgres.ColumnInteger
	LastSignedAt   postgres.ColumnTimestamp
	CreatedAt      postgres.ColumnTimestamp
	IssuanceEkus   postgres.ColumnString
	DeletedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CertificateAuthorityTable struct {
	certificateAuthorityTable

	EXCLUDED certificateAuthorityTable
}

// AS creates new CertificateAuthorityTable with assigned alias
func (a CertificateAuthorityTable) AS(alias string) *CertificateAuthorityTable {
	return newCertificateAuthorityTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CertificateAuthorityTable with assigned schema name
func (a CertificateAuthorityTable) FromSchema(schemaName string) *CertificateAuthorityTable {
	return newCertificateAuthorityTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CertificateAuthorityTable with assigned table prefix
func (a CertificateAuthorityTable) WithPrefix(prefix string) *CertificateAuthorityTable {
	return newCertificateAuthorityTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CertificateAuthorityTable with assigned table suffix
func (a CertificateAuthorityTable) WithSuffix(suffix string) *CertificateAuthorityTable {
	return newCertificateAuthorityTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCertificateAuthorityTable(schemaName, tableName, alias string) *CertificateAuthorityTable {
	return &CertificateAuthorityTable{
		certificateAuthorityTable: newCertificateAuthorityTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newCertificateAuthorityTableImpl("", "excluded", ""),
	}
}

func newCertificateAuthorityTableImpl(schemaName, tableName, alias string) certificateAuthorityTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		ParentIDColumn       = postgres.StringColumn("parent_id")
		NameColumn           = postgres.StringColumn("name")
		TypeColumn           = postgres.StringColumn("type")
		StatusColumn         = postgres.StringColumn("status")
		SubjectColumn        = postgres.StringColumn("subject")
		AlgorithmColumn      = postgres.StringColumn("algorithm")
		KmsKeyVersionColumn  = postgres.StringColumn("kms_key_version")
		CertificatePemColumn = postgres.StringColumn("certificate_pem")
		ChainPemColumn       = postgres.StringColumn("chain_pem")
		ExportPostureColumn  = postgres.StringColumn("export_posture")
		NotBeforeColumn      = postgres.TimestampColumn("not_before")
		NotAfterColumn       = postgres.TimestampColumn("not_after")
		IssuedCountColumn    = postgres.IntegerColumn("issued_count")
		LastSignedAtColumn   = postgres.TimestampColumn("last_signed_at")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		IssuanceEkusColumn   = postgres.StringColumn("issuance_ekus")
		DeletedAtColumn      = postgres.TimestampColumn("deleted_at")
		allColumns           = postgres.ColumnList{IDColumn, OrganizationIDColumn, ParentIDColumn, NameColumn, TypeColumn, StatusColumn, SubjectColumn, AlgorithmColumn, KmsKeyVersionColumn, CertificatePemColumn, ChainPemColumn, ExportPostureColumn, NotBeforeColumn, NotAfterColumn, IssuedCountColumn, LastSignedAtColumn, CreatedAtColumn, IssuanceEkusColumn, DeletedAtColumn}
		mutableColumns       = postgres.ColumnList{OrganizationIDColumn, ParentIDColumn, NameColumn, TypeColumn, StatusColumn, SubjectColumn, AlgorithmColumn, KmsKeyVersionColumn, CertificatePemColumn, ChainPemColumn, ExportPostureColumn, NotBeforeColumn, NotAfterColumn, IssuedCountColumn, LastSignedAtColumn, CreatedAtColumn, IssuanceEkusColumn, DeletedAtColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, StatusColumn, ExportPostureColumn, IssuedCountColumn, CreatedAtColumn, IssuanceEkusColumn}
	)

	return certificateAuthorityTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OrganizationID: OrganizationIDColumn,
		ParentID:       ParentIDColumn,
		Name:           NameColumn,
		Type:           TypeColumn,
		Status:         StatusColumn,
		Subject:        SubjectColumn,
		Algorithm:      AlgorithmColumn,
		KmsKeyVersion:  KmsKeyVersionColumn,
		CertificatePem: CertificatePemColumn,
		ChainPem:       ChainPemColumn,
		ExportPosture:  ExportPostureColumn,
		NotBefore:      NotBeforeColumn,
		NotAfter:       NotAfterColumn,
		IssuedCount:    IssuedCountColumn,
		LastSignedAt:   LastSignedAtColumn,
		CreatedAt:      CreatedAtColumn,
		IssuanceEkus:   IssuanceEkusColumn,
		DeletedAt:      DeletedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
