//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CertificateRevocation = newCertificateRevocationTable("public", "certificate_revocation", "")

type certificateRevocationTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OrganizationID postgres.ColumnString
	CertificateID  postgres.ColumnString
	Reason         postgres.ColumnString
	RevokedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CertificateRevocationTable struct {
	certificateRevocationTable

	EXCLUDED certificateRevocationTable
}

// AS creates new CertificateRevocationTable with assigned alias
func (a CertificateRevocationTable) AS(alias string) *CertificateRevocationTable {
	return newCertificateRevocationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CertificateRevocationTable with assigned schema name
func (a CertificateRevocationTable) FromSchema(schemaName string) *CertificateRevocationTable {
	return newCertificateRevocationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CertificateRevocationTable with assigned table prefix
func (a CertificateRevocationTable) WithPrefix(prefix string) *CertificateRevocationTable {
	return newCertificateRevocationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CertificateRevocationTable with assigned table suffix
func (a CertificateRevocationTable) WithSuffix(suffix string) *CertificateRevocationTable {
	return newCertificateRevocationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCertificateRevocationTable(schemaName, tableName, alias string) *CertificateRevocationTable {
	return &CertificateRevocationTable{
		certificateRevocationTable: newCertificateRevocationTableImpl(schemaName, tableName, alias),
		EXCLUDED:                   newCertificateRevocationTableImpl("", "excluded", ""),
	}
}

func newCertificateRevocationTableImpl(schemaName, tableName, alias string) certificateRevocationTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		CertificateIDColumn  = postgres.StringColumn("certificate_id")
		ReasonColumn         = postgres.StringColumn("reason")
		RevokedAtColumn      = postgres.TimestampColumn("revoked_at")
		allColumns           = postgres.ColumnList{IDColumn, OrganizationIDColumn, CertificateIDColumn, ReasonColumn, RevokedAtColumn}
		mutableColumns       = postgres.ColumnList{OrganizationIDColumn, CertificateIDColumn, ReasonColumn, RevokedAtColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, RevokedAtColumn}
	)

	return certificateRevocationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OrganizationID: OrganizationIDColumn,
		CertificateID:  CertificateIDColumn,
		Reason:         ReasonColumn,
		RevokedAt:      RevokedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
