//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Certificate = newCertificateTable("public", "certificate", "")

type certificateTable struct {
	postgres.Table

	// Columns
	ID                     postgres.ColumnString
	OrganizationID         postgres.ColumnString
	CertificateAuthorityID postgres.ColumnString
	Serial                 postgres.ColumnString
	Subject                postgres.ColumnString
	Sans                   postgres.ColumnString
	Status                 postgres.ColumnString
	CsrDigest              postgres.ColumnString
	CertificatePem         postgres.ColumnString
	ChainPem               postgres.ColumnString
	IssuedAt               postgres.ColumnTimestamp
	RevokedAt              postgres.ColumnTimestamp
	ExpiresAt              postgres.ColumnTimestamp
	Profile                postgres.ColumnString
	Ekus                   postgres.ColumnString
	ExpiryNotifiedAt       postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CertificateTable struct {
	certificateTable

	EXCLUDED certificateTable
}

// AS creates new CertificateTable with assigned alias
func (a CertificateTable) AS(alias string) *CertificateTable {
	return newCertificateTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CertificateTable with assigned schema name
func (a CertificateTable) FromSchema(schemaName string) *CertificateTable {
	return newCertificateTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CertificateTable with assigned table prefix
func (a CertificateTable) WithPrefix(prefix string) *CertificateTable {
	return newCertificateTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CertificateTable with assigned table suffix
func (a CertificateTable) WithSuffix(suffix string) *CertificateTable {
	return newCertificateTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCertificateTable(schemaName, tableName, alias string) *CertificateTable {
	return &CertificateTable{
		certificateTable: newCertificateTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newCertificateTableImpl("", "excluded", ""),
	}
}

func newCertificateTableImpl(schemaName, tableName, alias string) certificateTable {
	var (
		IDColumn                     = postgres.StringColumn("id")
		OrganizationIDColumn         = postgres.StringColumn("organization_id")
		CertificateAuthorityIDColumn = postgres.StringColumn("certificate_authority_id")
		SerialColumn                 = postgres.StringColumn("serial")
		SubjectColumn                = postgres.StringColumn("subject")
		SansColumn                   = postgres.StringColumn("sans")
		StatusColumn                 = postgres.StringColumn("status")
		CsrDigestColumn              = postgres.StringColumn("csr_digest")
		CertificatePemColumn         = postgres.StringColumn("certificate_pem")
		ChainPemColumn               = postgres.StringColumn("chain_pem")
		IssuedAtColumn               = postgres.TimestampColumn("issued_at")
		RevokedAtColumn              = postgres.TimestampColumn("revoked_at")
		ExpiresAtColumn              = postgres.TimestampColumn("expires_at")
		ProfileColumn                = postgres.StringColumn("profile")
		EkusColumn                   = postgres.StringColumn("ekus")
		ExpiryNotifiedAtColumn       = postgres.TimestampzColumn("expiry_notified_at")
		allColumns                   = postgres.ColumnList{IDColumn, OrganizationIDColumn, CertificateAuthorityIDColumn, SerialColumn, SubjectColumn, SansColumn, StatusColumn, CsrDigestColumn, CertificatePemColumn, ChainPemColumn, IssuedAtColumn, RevokedAtColumn, ExpiresAtColumn, ProfileColumn, EkusColumn, ExpiryNotifiedAtColumn}
		mutableColumns               = postgres.ColumnList{OrganizationIDColumn, CertificateAuthorityIDColumn, SerialColumn, SubjectColumn, SansColumn, StatusColumn, CsrDigestColumn, CertificatePemColumn, ChainPemColumn, IssuedAtColumn, RevokedAtColumn, ExpiresAtColumn, ProfileColumn, EkusColumn, ExpiryNotifiedAtColumn}
		defaultColumns               = postgres.ColumnList{IDColumn, SansColumn, StatusColumn, IssuedAtColumn, ProfileColumn, EkusColumn}
	)

	return certificateTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		OrganizationID:         OrganizationIDColumn,
		CertificateAuthorityID: CertificateAuthorityIDColumn,
		Serial:                 SerialColumn,
		Subject:                SubjectColumn,
		Sans:                   SansColumn,
		Status:                 StatusColumn,
		CsrDigest:              CsrDigestColumn,
		CertificatePem:         CertificatePemColumn,
		ChainPem:               ChainPemColumn,
		IssuedAt:               IssuedAtColumn,
		RevokedAt:              RevokedAtColumn,
		ExpiresAt:              ExpiresAtColumn,
		Profile:                ProfileColumn,
		Ekus:                   EkusColumn,
		ExpiryNotifiedAt:       ExpiryNotifiedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
