//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CertificateSigningAudit = newCertificateSigningAuditTable("public", "certificate_signing_audit", "")

type certificateSigningAuditTable struct {
	postgres.Table

	// Columns
	ID                     postgres.ColumnString
	OrganizationID         postgres.ColumnString
	CertificateAuthorityID postgres.ColumnString
	RequesterUserID        postgres.ColumnString
	KmsKeyVersion          postgres.ColumnString
	CsrDigest              postgres.ColumnString
	CertificateSerial      postgres.ColumnString
	Purpose                postgres.ColumnString
	SignedAt               postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CertificateSigningAuditTable struct {
	certificateSigningAuditTable

	EXCLUDED certificateSigningAuditTable
}

// AS creates new CertificateSigningAuditTable with assigned alias
func (a CertificateSigningAuditTable) AS(alias string) *CertificateSigningAuditTable {
	return newCertificateSigningAuditTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CertificateSigningAuditTable with assigned schema name
func (a CertificateSigningAuditTable) FromSchema(schemaName string) *CertificateSigningAuditTable {
	return newCertificateSigningAuditTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CertificateSigningAuditTable with assigned table prefix
func (a CertificateSigningAuditTable) WithPrefix(prefix string) *CertificateSigningAuditTable {
	return newCertificateSigningAuditTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CertificateSigningAuditTable with assigned table suffix
func (a CertificateSigningAuditTable) WithSuffix(suffix string) *CertificateSigningAuditTable {
	return newCertificateSigningAuditTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCertificateSigningAuditTable(schemaName, tableName, alias string) *CertificateSigningAuditTable {
	return &CertificateSigningAuditTable{
		certificateSigningAuditTable: newCertificateSigningAuditTableImpl(schemaName, tableName, alias),
		EXCLUDED:                     newCertificateSigningAuditTableImpl("", "excluded", ""),
	}
}

func newCertificateSigningAuditTableImpl(schemaName, tableName, alias string) certificateSigningAuditTable {
	var (
		IDColumn                     = postgres.StringColumn("id")
		OrganizationIDColumn         = postgres.StringColumn("organization_id")
		CertificateAuthorityIDColumn = postgres.StringColumn("certificate_authority_id")
		RequesterUserIDColumn        = postgres.StringColumn("requester_user_id")
		KmsKeyVersionColumn          = postgres.StringColumn("kms_key_version")
		CsrDigestColumn              = postgres.StringColumn("csr_digest")
		CertificateSerialColumn      = postgres.StringColumn("certificate_serial")
		PurposeColumn                = postgres.StringColumn("purpose")
		SignedAtColumn               = postgres.TimestampzColumn("signed_at")
		allColumns                   = postgres.ColumnList{IDColumn, OrganizationIDColumn, CertificateAuthorityIDColumn, RequesterUserIDColumn, KmsKeyVersionColumn, CsrDigestColumn, CertificateSerialColumn, PurposeColumn, SignedAtColumn}
		mutableColumns               = postgres.ColumnList{OrganizationIDColumn, CertificateAuthorityIDColumn, RequesterUserIDColumn, KmsKeyVersionColumn, CsrDigestColumn, CertificateSerialColumn, PurposeColumn, SignedAtColumn}
		defaultColumns               = postgres.ColumnList{IDColumn, SignedAtColumn}
	)

	return certificateSigningAuditTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		OrganizationID:         OrganizationIDColumn,
		CertificateAuthorityID: CertificateAuthorityIDColumn,
		RequesterUserID:        RequesterUserIDColumn,
		KmsKeyVersion:          KmsKeyVersionColumn,
		CsrDigest:              CsrDigestColumn,
		CertificateSerial:      CertificateSerialColumn,
		Purpose:                PurposeColumn,
		SignedAt:               SignedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
