//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CrlPublication = newCrlPublicationTable("public", "crl_publication", "")

type crlPublicationTable struct {
	postgres.Table

	// Columns
	OrganizationID         postgres.ColumnString
	CertificateAuthorityID postgres.ColumnString
	CrlDer                 postgres.ColumnBytea
	CrlNumber              postgres.ColumnInteger
	ThisUpdate             postgres.ColumnTimestamp
	NextUpdate             postgres.ColumnTimestamp
	PublishedAt            postgres.ColumnTimestamp
	LastAttemptAt          postgres.ColumnTimestamp
	LastError              postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CrlPublicationTable struct {
	crlPublicationTable

	EXCLUDED crlPublicationTable
}

// AS creates new CrlPublicationTable with assigned alias
func (a CrlPublicationTable) AS(alias string) *CrlPublicationTable {
	return newCrlPublicationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CrlPublicationTable with assigned schema name
func (a CrlPublicationTable) FromSchema(schemaName string) *CrlPublicationTable {
	return newCrlPublicationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CrlPublicationTable with assigned table prefix
func (a CrlPublicationTable) WithPrefix(prefix string) *CrlPublicationTable {
	return newCrlPublicationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CrlPublicationTable with assigned table suffix
func (a CrlPublicationTable) WithSuffix(suffix string) *CrlPublicationTable {
	return newCrlPublicationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCrlPublicationTable(schemaName, tableName, alias string) *CrlPublicationTable {
	return &CrlPublicationTable{
		crlPublicationTable: newCrlPublicationTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newCrlPublicationTableImpl("", "excluded", ""),
	}
}

func newCrlPublicationTableImpl(schemaName, tableName, alias string) crlPublicationTable {
	var (
		OrganizationIDColumn         = postgres.StringColumn("organization_id")
		CertificateAuthorityIDColumn = postgres.StringColumn("certificate_authority_id")
		CrlDerColumn                 = postgres.ByteaColumn("crl_der")
		CrlNumberColumn              = postgres.IntegerColumn("crl_number")
		ThisUpdateColumn             = postgres.TimestampColumn("this_update")
		NextUpdateColumn             = postgres.TimestampColumn("next_update")
		PublishedAtColumn            = postgres.TimestampColumn("published_at")
		LastAttemptAtColumn          = postgres.TimestampColumn("last_attempt_at")
		LastErrorColumn              = postgres.StringColumn("last_error")
		allColumns                   = postgres.ColumnList{OrganizationIDColumn, CertificateAuthorityIDColumn, CrlDerColumn, CrlNumberColumn, ThisUpdateColumn, NextUpdateColumn, PublishedAtColumn, LastAttemptAtColumn, LastErrorColumn}
		mutableColumns               = postgres.ColumnList{OrganizationIDColumn, CrlDerColumn, CrlNumberColumn, ThisUpdateColumn, NextUpdateColumn, PublishedAtColumn, LastAttemptAtColumn, LastErrorColumn}
		defaultColumns               = postgres.ColumnList{CrlDerColumn, CrlNumberColumn, LastErrorColumn}
	)

	return crlPublicationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		OrganizationID:         OrganizationIDColumn,
		CertificateAuthorityID: CertificateAuthorityIDColumn,
		CrlDer:                 CrlDerColumn,
		CrlNumber:              CrlNumberColumn,
		ThisUpdate:             ThisUpdateColumn,
		NextUpdate:             NextUpdateColumn,
		PublishedAt:            PublishedAtColumn,
		LastAttemptAt:          LastAttemptAtColumn,
		LastError:              LastErrorColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
