//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EmailInvitation = newEmailInvitationTable("public", "email_invitation", "")

type emailInvitationTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OrganizationID postgres.ColumnString
	Email          postgres.ColumnString
	Role           postgres.ColumnString
	ExpiresAt      postgres.ColumnTimestamp
	AcceptedAt     postgres.ColumnTimestamp
	CreatedAt      postgres.ColumnTimestamp
	TokenHash      postgres.ColumnString
	Name           postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EmailInvitationTable struct {
	emailInvitationTable

	EXCLUDED emailInvitationTable
}

// AS creates new EmailInvitationTable with assigned alias
func (a EmailInvitationTable) AS(alias string) *EmailInvitationTable {
	return newEmailInvitationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EmailInvitationTable with assigned schema name
func (a EmailInvitationTable) FromSchema(schemaName string) *EmailInvitationTable {
	return newEmailInvitationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EmailInvitationTable with assigned table prefix
func (a EmailInvitationTable) WithPrefix(prefix string) *EmailInvitationTable {
	return newEmailInvitationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EmailInvitationTable with assigned table suffix
func (a EmailInvitationTable) WithSuffix(suffix string) *EmailInvitationTable {
	return newEmailInvitationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEmailInvitationTable(schemaName, tableName, alias string) *EmailInvitationTable {
	return &EmailInvitationTable{
		emailInvitationTable: newEmailInvitationTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newEmailInvitationTableImpl("", "excluded", ""),
	}
}

func newEmailInvitationTableImpl(schemaName, tableName, alias string) emailInvitationTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		EmailColumn          = postgres.StringColumn("email")
		RoleColumn           = postgres.StringColumn("role")
		ExpiresAtColumn      = postgres.TimestampColumn("expires_at")
		AcceptedAtColumn     = postgres.TimestampColumn("accepted_at")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		TokenHashColumn      = postgres.StringColumn("token_hash")
		NameColumn           = postgres.StringColumn("name")
		allColumns           = postgres.ColumnList{IDColumn, OrganizationIDColumn, EmailColumn, RoleColumn, ExpiresAtColumn, AcceptedAtColumn, CreatedAtColumn, TokenHashColumn, NameColumn}
		mutableColumns       = postgres.ColumnList{OrganizationIDColumn, EmailColumn, RoleColumn, ExpiresAtColumn, AcceptedAtColumn, CreatedAtColumn, TokenHashColumn, NameColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, RoleColumn, CreatedAtColumn}
	)

	return emailInvitationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OrganizationID: OrganizationIDColumn,
		Email:          EmailColumn,
		Role:           RoleColumn,
		ExpiresAt:      ExpiresAtColumn,
		AcceptedAt:     AcceptedAtColumn,
		CreatedAt:      CreatedAtColumn,
		TokenHash:      TokenHashColumn,
		Name:           NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
