//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EstCredential = newEstCredentialTable("public", "est_credential", "")

type estCredentialTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OrganizationID postgres.ColumnString
	EstEndpointID  postgres.ColumnString
	Label          postgres.ColumnString
	Username       postgres.ColumnString
	SecretHash     postgres.ColumnString
	IdentifierPin  postgres.ColumnString
	ExpiresAt      postgres.ColumnTimestamp
	UsedAt         postgres.ColumnTimestamp
	RevokedAt      postgres.ColumnTimestamp
	CreatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EstCredentialTable struct {
	estCredentialTable

	EXCLUDED estCredentialTable
}

// AS creates new EstCredentialTable with assigned alias
func (a EstCredentialTable) AS(alias string) *EstCredentialTable {
	return newEstCredentialTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EstCredentialTable with assigned schema name
func (a EstCredentialTable) FromSchema(schemaName string) *EstCredentialTable {
	return newEstCredentialTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EstCredentialTable with assigned table prefix
func (a EstCredentialTable) WithPrefix(prefix string) *EstCredentialTable {
	return newEstCredentialTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EstCredentialTable with assigned table suffix
func (a EstCredentialTable) WithSuffix(suffix string) *EstCredentialTable {
	return newEstCredentialTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEstCredentialTable(schemaName, tableName, alias string) *EstCredentialTable {
	return &EstCredentialTable{
		estCredentialTable: newEstCredentialTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newEstCredentialTableImpl("", "excluded", ""),
	}
}

func newEstCredentialTableImpl(schemaName, tableName, alias string) estCredentialTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		EstEndpointIDColumn  = postgres.StringColumn("est_endpoint_id")
		LabelColumn          = postgres.StringColumn("label")
		UsernameColumn       = postgres.StringColumn("username")
		SecretHashColumn     = postgres.StringColumn("secret_hash")
		IdentifierPinColumn  = postgres.StringColumn("identifier_pin")
		ExpiresAtColumn      = postgres.TimestampColumn("expires_at")
		UsedAtColumn         = postgres.TimestampColumn("used_at")
		RevokedAtColumn      = postgres.TimestampColumn("revoked_at")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		allColumns           = postgres.ColumnList{IDColumn, OrganizationIDColumn, EstEndpointIDColumn, LabelColumn, UsernameColumn, SecretHashColumn, IdentifierPinColumn, ExpiresAtColumn, UsedAtColumn, RevokedAtColumn, CreatedAtColumn}
		mutableColumns       = postgres.ColumnList{OrganizationIDColumn, EstEndpointIDColumn, LabelColumn, UsernameColumn, SecretHashColumn, IdentifierPinColumn, ExpiresAtColumn, UsedAtColumn, RevokedAtColumn, CreatedAtColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, LabelColumn, IdentifierPinColumn, CreatedAtColumn}
	)

	return estCredentialTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OrganizationID: OrganizationIDColumn,
		EstEndpointID:  EstEndpointIDColumn,
		Label:          LabelColumn,
		Username:       UsernameColumn,
		SecretHash:     SecretHashColumn,
		IdentifierPin:  IdentifierPinColumn,
		ExpiresAt:      ExpiresAtColumn,
		UsedAt:         UsedAtColumn,
		RevokedAt:      RevokedAtColumn,
		CreatedAt:      CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
