//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EstEndpoint = newEstEndpointTable("public", "est_endpoint", "")

type estEndpointTable struct {
	postgres.Table

	// Columns
	ID                      postgres.ColumnString
	OrganizationID          postgres.ColumnString
	CertificateAuthorityID  postgres.ColumnString
	Name                    postgres.ColumnString
	Enabled                 postgres.ColumnBool
	ValidityDays            postgres.ColumnInteger
	RenewalWindowDays       postgres.ColumnInteger
	AllowedEkus             postgres.ColumnString
	SubjectPattern          postgres.ColumnString
	SanPattern              postgres.ColumnString
	CreatedAt               postgres.ColumnTimestamp
	UpdatedAt               postgres.ColumnTimestamp
	ReenrollRequiresSameKey postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EstEndpointTable struct {
	estEndpointTable

	EXCLUDED estEndpointTable
}

// AS creates new EstEndpointTable with assigned alias
func (a EstEndpointTable) AS(alias string) *EstEndpointTable {
	return newEstEndpointTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EstEndpointTable with assigned schema name
func (a EstEndpointTable) FromSchema(schemaName string) *EstEndpointTable {
	return newEstEndpointTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EstEndpointTable with assigned table prefix
func (a EstEndpointTable) WithPrefix(prefix string) *EstEndpointTable {
	return newEstEndpointTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EstEndpointTable with assigned table suffix
func (a EstEndpointTable) WithSuffix(suffix string) *EstEndpointTable {
	return newEstEndpointTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEstEndpointTable(schemaName, tableName, alias string) *EstEndpointTable {
	return &EstEndpointTable{
		estEndpointTable: newEstEndpointTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newEstEndpointTableImpl("", "excluded", ""),
	}
}

func newEstEndpointTableImpl(schemaName, tableName, alias string) estEndpointTable {
	var (
		IDColumn                      = postgres.StringColumn("id")
		OrganizationIDColumn          = postgres.StringColumn("organization_id")
		CertificateAuthorityIDColumn  = postgres.StringColumn("certificate_authority_id")
		NameColumn                    = postgres.StringColumn("name")
		EnabledColumn                 = postgres.BoolColumn("enabled")
		ValidityDaysColumn            = postgres.IntegerColumn("validity_days")
		RenewalWindowDaysColumn       = postgres.IntegerColumn("renewal_window_days")
		AllowedEkusColumn             = postgres.StringColumn("allowed_ekus")
		SubjectPatternColumn          = postgres.StringColumn("subject_pattern")
		SanPatternColumn              = postgres.StringColumn("san_pattern")
		CreatedAtColumn               = postgres.TimestampColumn("created_at")
		UpdatedAtColumn               = postgres.TimestampColumn("updated_at")
		ReenrollRequiresSameKeyColumn = postgres.BoolColumn("reenroll_requires_same_key")
		allColumns                    = postgres.ColumnList{IDColumn, OrganizationIDColumn, CertificateAuthorityIDColumn, NameColumn, EnabledColumn, ValidityDaysColumn, RenewalWindowDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, CreatedAtColumn, UpdatedAtColumn, ReenrollRequiresSameKeyColumn}
		mutableColumns                = postgres.ColumnList{OrganizationIDColumn, CertificateAuthorityIDColumn, NameColumn, EnabledColumn, ValidityDaysColumn, RenewalWindowDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, CreatedAtColumn, UpdatedAtColumn, ReenrollRequiresSameKeyColumn}
		defaultColumns                = postgres.ColumnList{IDColumn, EnabledColumn, ValidityDaysColumn, RenewalWindowDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, CreatedAtColumn, UpdatedAtColumn, ReenrollRequiresSameKeyColumn}
	)

	return estEndpointTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                      IDColumn,
		OrganizationID:          OrganizationIDColumn,
		CertificateAuthorityID:  CertificateAuthorityIDColumn,
		Name:                    NameColumn,
		Enabled:                 EnabledColumn,
		ValidityDays:            ValidityDaysColumn,
		RenewalWindowDays:       RenewalWindowDaysColumn,
		AllowedEkus:             AllowedEkusColumn,
		SubjectPattern:          SubjectPatternColumn,
		SanPattern:              SanPatternColumn,
		CreatedAt:               CreatedAtColumn,
		UpdatedAt:               UpdatedAtColumn,
		ReenrollRequiresSameKey: ReenrollRequiresSameKeyColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
