//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var EstEnrollment = newEstEnrollmentTable("public", "est_enrollment", "")

type estEnrollmentTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	OrganizationID  postgres.ColumnString
	EstEndpointID   postgres.ColumnString
	EstCredentialID postgres.ColumnString
	CertificateID   postgres.ColumnString
	Subject         postgres.ColumnString
	Operation       postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	Status          postgres.ColumnString
	FailureReason   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type EstEnrollmentTable struct {
	estEnrollmentTable

	EXCLUDED estEnrollmentTable
}

// AS creates new EstEnrollmentTable with assigned alias
func (a EstEnrollmentTable) AS(alias string) *EstEnrollmentTable {
	return newEstEnrollmentTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EstEnrollmentTable with assigned schema name
func (a EstEnrollmentTable) FromSchema(schemaName string) *EstEnrollmentTable {
	return newEstEnrollmentTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EstEnrollmentTable with assigned table prefix
func (a EstEnrollmentTable) WithPrefix(prefix string) *EstEnrollmentTable {
	return newEstEnrollmentTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EstEnrollmentTable with assigned table suffix
func (a EstEnrollmentTable) WithSuffix(suffix string) *EstEnrollmentTable {
	return newEstEnrollmentTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEstEnrollmentTable(schemaName, tableName, alias string) *EstEnrollmentTable {
	return &EstEnrollmentTable{
		estEnrollmentTable: newEstEnrollmentTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newEstEnrollmentTableImpl("", "excluded", ""),
	}
}

func newEstEnrollmentTableImpl(schemaName, tableName, alias string) estEnrollmentTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		OrganizationIDColumn  = postgres.StringColumn("organization_id")
		EstEndpointIDColumn   = postgres.StringColumn("est_endpoint_id")
		EstCredentialIDColumn = postgres.StringColumn("est_credential_id")
		CertificateIDColumn   = postgres.StringColumn("certificate_id")
		SubjectColumn         = postgres.StringColumn("subject")
		OperationColumn       = postgres.StringColumn("operation")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		StatusColumn          = postgres.StringColumn("status")
		FailureReasonColumn   = postgres.StringColumn("failure_reason")
		allColumns            = postgres.ColumnList{IDColumn, OrganizationIDColumn, EstEndpointIDColumn, EstCredentialIDColumn, CertificateIDColumn, SubjectColumn, OperationColumn, CreatedAtColumn, StatusColumn, FailureReasonColumn}
		mutableColumns        = postgres.ColumnList{OrganizationIDColumn, EstEndpointIDColumn, EstCredentialIDColumn, CertificateIDColumn, SubjectColumn, OperationColumn, CreatedAtColumn, StatusColumn, FailureReasonColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, SubjectColumn, CreatedAtColumn, StatusColumn, FailureReasonColumn}
	)

	return estEnrollmentTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		OrganizationID:  OrganizationIDColumn,
		EstEndpointID:   EstEndpointIDColumn,
		EstCredentialID: EstCredentialIDColumn,
		CertificateID:   CertificateIDColumn,
		Subject:         SubjectColumn,
		Operation:       OperationColumn,
		CreatedAt:       CreatedAtColumn,
		Status:          StatusColumn,
		FailureReason:   FailureReasonColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
