//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var LoginChallenge = newLoginChallengeTable("public", "login_challenge", "")

type loginChallengeTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	UserID            postgres.ColumnString
	Stage             postgres.ColumnString
	PendingTotpSecret postgres.ColumnBytea
	Attempts          postgres.ColumnInteger
	WebauthnSession   postgres.ColumnString
	ExpiresAt         postgres.ColumnTimestamp
	CreatedAt         postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LoginChallengeTable struct {
	loginChallengeTable

	EXCLUDED loginChallengeTable
}

// AS creates new LoginChallengeTable with assigned alias
func (a LoginChallengeTable) AS(alias string) *LoginChallengeTable {
	return newLoginChallengeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new LoginChallengeTable with assigned schema name
func (a LoginChallengeTable) FromSchema(schemaName string) *LoginChallengeTable {
	return newLoginChallengeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new LoginChallengeTable with assigned table prefix
func (a LoginChallengeTable) WithPrefix(prefix string) *LoginChallengeTable {
	return newLoginChallengeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new LoginChallengeTable with assigned table suffix
func (a LoginChallengeTable) WithSuffix(suffix string) *LoginChallengeTable {
	return newLoginChallengeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newLoginChallengeTable(schemaName, tableName, alias string) *LoginChallengeTable {
	return &LoginChallengeTable{
		loginChallengeTable: newLoginChallengeTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newLoginChallengeTableImpl("", "excluded", ""),
	}
}

func newLoginChallengeTableImpl(schemaName, tableName, alias string) loginChallengeTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		UserIDColumn            = postgres.StringColumn("user_id")
		StageColumn             = postgres.StringColumn("stage")
		PendingTotpSecretColumn = postgres.ByteaColumn("pending_totp_secret")
		AttemptsColumn          = postgres.IntegerColumn("attempts")
		WebauthnSessionColumn   = postgres.StringColumn("webauthn_session")
		ExpiresAtColumn         = postgres.TimestampColumn("expires_at")
		CreatedAtColumn         = postgres.TimestampColumn("created_at")
		allColumns              = postgres.ColumnList{IDColumn, UserIDColumn, StageColumn, PendingTotpSecretColumn, AttemptsColumn, WebauthnSessionColumn, ExpiresAtColumn, CreatedAtColumn}
		mutableColumns          = postgres.ColumnList{UserIDColumn, StageColumn, PendingTotpSecretColumn, AttemptsColumn, WebauthnSessionColumn, ExpiresAtColumn, CreatedAtColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, AttemptsColumn, CreatedAtColumn}
	)

	return loginChallengeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		UserID:            UserIDColumn,
		Stage:             StageColumn,
		PendingTotpSecret: PendingTotpSecretColumn,
		Attempts:          AttemptsColumn,
		WebauthnSession:   WebauthnSessionColumn,
		ExpiresAt:         ExpiresAtColumn,
		CreatedAt:         CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
