//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var MagicLink = newMagicLinkTable("public", "magic_link", "")

type magicLinkTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	UserID    postgres.ColumnString
	ExpiresAt postgres.ColumnTimestamp
	TokenHash postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type MagicLinkTable struct {
	magicLinkTable

	EXCLUDED magicLinkTable
}

// AS creates new MagicLinkTable with assigned alias
func (a MagicLinkTable) AS(alias string) *MagicLinkTable {
	return newMagicLinkTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MagicLinkTable with assigned schema name
func (a MagicLinkTable) FromSchema(schemaName string) *MagicLinkTable {
	return newMagicLinkTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MagicLinkTable with assigned table prefix
func (a MagicLinkTable) WithPrefix(prefix string) *MagicLinkTable {
	return newMagicLinkTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MagicLinkTable with assigned table suffix
func (a MagicLinkTable) WithSuffix(suffix string) *MagicLinkTable {
	return newMagicLinkTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMagicLinkTable(schemaName, tableName, alias string) *MagicLinkTable {
	return &MagicLinkTable{
		magicLinkTable: newMagicLinkTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newMagicLinkTableImpl("", "excluded", ""),
	}
}

func newMagicLinkTableImpl(schemaName, tableName, alias string) magicLinkTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		UserIDColumn    = postgres.StringColumn("user_id")
		ExpiresAtColumn = postgres.TimestampColumn("expires_at")
		TokenHashColumn = postgres.StringColumn("token_hash")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, ExpiresAtColumn, TokenHashColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, ExpiresAtColumn, TokenHashColumn}
		defaultColumns  = postgres.ColumnList{IDColumn}
	)

	return magicLinkTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		ExpiresAt: ExpiresAtColumn,
		TokenHash: TokenHashColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
