//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var OcspResponseCache = newOcspResponseCacheTable("public", "ocsp_response_cache", "")

type ocspResponseCacheTable struct {
	postgres.Table

	// Columns
	OrganizationID         postgres.ColumnString
	CertificateAuthorityID postgres.ColumnString
	Serial                 postgres.ColumnString
	HashAlgorithm          postgres.ColumnInteger
	CertificateStatus      postgres.ColumnString
	ResponseDer            postgres.ColumnBytea
	ThisUpdate             postgres.ColumnTimestamp
	NextUpdate             postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OcspResponseCacheTable struct {
	ocspResponseCacheTable

	EXCLUDED ocspResponseCacheTable
}

// AS creates new OcspResponseCacheTable with assigned alias
func (a OcspResponseCacheTable) AS(alias string) *OcspResponseCacheTable {
	return newOcspResponseCacheTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OcspResponseCacheTable with assigned schema name
func (a OcspResponseCacheTable) FromSchema(schemaName string) *OcspResponseCacheTable {
	return newOcspResponseCacheTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OcspResponseCacheTable with assigned table prefix
func (a OcspResponseCacheTable) WithPrefix(prefix string) *OcspResponseCacheTable {
	return newOcspResponseCacheTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OcspResponseCacheTable with assigned table suffix
func (a OcspResponseCacheTable) WithSuffix(suffix string) *OcspResponseCacheTable {
	return newOcspResponseCacheTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOcspResponseCacheTable(schemaName, tableName, alias string) *OcspResponseCacheTable {
	return &OcspResponseCacheTable{
		ocspResponseCacheTable: newOcspResponseCacheTableImpl(schemaName, tableName, alias),
		EXCLUDED:               newOcspResponseCacheTableImpl("", "excluded", ""),
	}
}

func newOcspResponseCacheTableImpl(schemaName, tableName, alias string) ocspResponseCacheTable {
	var (
		OrganizationIDColumn         = postgres.StringColumn("organization_id")
		CertificateAuthorityIDColumn = postgres.StringColumn("certificate_authority_id")
		SerialColumn                 = postgres.StringColumn("serial")
		HashAlgorithmColumn          = postgres.IntegerColumn("hash_algorithm")
		CertificateStatusColumn      = postgres.StringColumn("certificate_status")
		ResponseDerColumn            = postgres.ByteaColumn("response_der")
		ThisUpdateColumn             = postgres.TimestampColumn("this_update")
		NextUpdateColumn             = postgres.TimestampColumn("next_update")
		allColumns                   = postgres.ColumnList{OrganizationIDColumn, CertificateAuthorityIDColumn, SerialColumn, HashAlgorithmColumn, CertificateStatusColumn, ResponseDerColumn, ThisUpdateColumn, NextUpdateColumn}
		mutableColumns               = postgres.ColumnList{OrganizationIDColumn, CertificateStatusColumn, ResponseDerColumn, ThisUpdateColumn, NextUpdateColumn}
		defaultColumns               = postgres.ColumnList{}
	)

	return ocspResponseCacheTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		OrganizationID:         OrganizationIDColumn,
		CertificateAuthorityID: CertificateAuthorityIDColumn,
		Serial:                 SerialColumn,
		HashAlgorithm:          HashAlgorithmColumn,
		CertificateStatus:      CertificateStatusColumn,
		ResponseDer:            ResponseDerColumn,
		ThisUpdate:             ThisUpdateColumn,
		NextUpdate:             NextUpdateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
