//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Organization = newOrganizationTable("public", "organization", "")

type organizationTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	Name                postgres.ColumnString
	ExpiryAlertsEnabled postgres.ColumnBool
	ExpiryAlertDays     postgres.ColumnInteger
	CreatedAt           postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type OrganizationTable struct {
	organizationTable

	EXCLUDED organizationTable
}

// AS creates new OrganizationTable with assigned alias
func (a OrganizationTable) AS(alias string) *OrganizationTable {
	return newOrganizationTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OrganizationTable with assigned schema name
func (a OrganizationTable) FromSchema(schemaName string) *OrganizationTable {
	return newOrganizationTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OrganizationTable with assigned table prefix
func (a OrganizationTable) WithPrefix(prefix string) *OrganizationTable {
	return newOrganizationTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OrganizationTable with assigned table suffix
func (a OrganizationTable) WithSuffix(suffix string) *OrganizationTable {
	return newOrganizationTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOrganizationTable(schemaName, tableName, alias string) *OrganizationTable {
	return &OrganizationTable{
		organizationTable: newOrganizationTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newOrganizationTableImpl("", "excluded", ""),
	}
}

func newOrganizationTableImpl(schemaName, tableName, alias string) organizationTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		NameColumn                = postgres.StringColumn("name")
		ExpiryAlertsEnabledColumn = postgres.BoolColumn("expiry_alerts_enabled")
		ExpiryAlertDaysColumn     = postgres.IntegerColumn("expiry_alert_days")
		CreatedAtColumn           = postgres.TimestampzColumn("created_at")
		allColumns                = postgres.ColumnList{IDColumn, NameColumn, ExpiryAlertsEnabledColumn, ExpiryAlertDaysColumn, CreatedAtColumn}
		mutableColumns            = postgres.ColumnList{NameColumn, ExpiryAlertsEnabledColumn, ExpiryAlertDaysColumn, CreatedAtColumn}
		defaultColumns            = postgres.ColumnList{IDColumn, ExpiryAlertsEnabledColumn, ExpiryAlertDaysColumn, CreatedAtColumn}
	)

	return organizationTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		Name:                NameColumn,
		ExpiryAlertsEnabled: ExpiryAlertsEnabledColumn,
		ExpiryAlertDays:     ExpiryAlertDaysColumn,
		CreatedAt:           CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
