//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScepIntuneConnection = newScepIntuneConnectionTable("public", "scep_intune_connection", "")

type scepIntuneConnectionTable struct {
	postgres.Table

	// Columns
	OrganizationID postgres.ColumnString
	TenantID       postgres.ColumnString
	ConnectedAt    postgres.ColumnTimestamp
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScepIntuneConnectionTable struct {
	scepIntuneConnectionTable

	EXCLUDED scepIntuneConnectionTable
}

// AS creates new ScepIntuneConnectionTable with assigned alias
func (a ScepIntuneConnectionTable) AS(alias string) *ScepIntuneConnectionTable {
	return newScepIntuneConnectionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScepIntuneConnectionTable with assigned schema name
func (a ScepIntuneConnectionTable) FromSchema(schemaName string) *ScepIntuneConnectionTable {
	return newScepIntuneConnectionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScepIntuneConnectionTable with assigned table prefix
func (a ScepIntuneConnectionTable) WithPrefix(prefix string) *ScepIntuneConnectionTable {
	return newScepIntuneConnectionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScepIntuneConnectionTable with assigned table suffix
func (a ScepIntuneConnectionTable) WithSuffix(suffix string) *ScepIntuneConnectionTable {
	return newScepIntuneConnectionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScepIntuneConnectionTable(schemaName, tableName, alias string) *ScepIntuneConnectionTable {
	return &ScepIntuneConnectionTable{
		scepIntuneConnectionTable: newScepIntuneConnectionTableImpl(schemaName, tableName, alias),
		EXCLUDED:                  newScepIntuneConnectionTableImpl("", "excluded", ""),
	}
}

func newScepIntuneConnectionTableImpl(schemaName, tableName, alias string) scepIntuneConnectionTable {
	var (
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		TenantIDColumn       = postgres.StringColumn("tenant_id")
		ConnectedAtColumn    = postgres.TimestampColumn("connected_at")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{OrganizationIDColumn, TenantIDColumn, ConnectedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{TenantIDColumn, ConnectedAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{ConnectedAtColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return scepIntuneConnectionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		OrganizationID: OrganizationIDColumn,
		TenantID:       TenantIDColumn,
		ConnectedAt:    ConnectedAtColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
