//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScepTransaction = newScepTransactionTable("public", "scep_transaction", "")

type scepTransactionTable struct {
	postgres.Table

	// Columns
	ID                  postgres.ColumnString
	OrganizationID      postgres.ColumnString
	ScepEndpointID      postgres.ColumnString
	TransactionID       postgres.ColumnString
	CsrDigest           postgres.ColumnString
	CertificateID       postgres.ColumnString
	MessageType         postgres.ColumnString
	Status              postgres.ColumnString
	AuthorizationSource postgres.ColumnString
	FailureReason       postgres.ColumnString
	CreatedAt           postgres.ColumnTimestamp
	UpdatedAt           postgres.ColumnTimestamp
	SignerKeyDigest     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScepTransactionTable struct {
	scepTransactionTable

	EXCLUDED scepTransactionTable
}

// AS creates new ScepTransactionTable with assigned alias
func (a ScepTransactionTable) AS(alias string) *ScepTransactionTable {
	return newScepTransactionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScepTransactionTable with assigned schema name
func (a ScepTransactionTable) FromSchema(schemaName string) *ScepTransactionTable {
	return newScepTransactionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScepTransactionTable with assigned table prefix
func (a ScepTransactionTable) WithPrefix(prefix string) *ScepTransactionTable {
	return newScepTransactionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScepTransactionTable with assigned table suffix
func (a ScepTransactionTable) WithSuffix(suffix string) *ScepTransactionTable {
	return newScepTransactionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScepTransactionTable(schemaName, tableName, alias string) *ScepTransactionTable {
	return &ScepTransactionTable{
		scepTransactionTable: newScepTransactionTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newScepTransactionTableImpl("", "excluded", ""),
	}
}

func newScepTransactionTableImpl(schemaName, tableName, alias string) scepTransactionTable {
	var (
		IDColumn                  = postgres.StringColumn("id")
		OrganizationIDColumn      = postgres.StringColumn("organization_id")
		ScepEndpointIDColumn      = postgres.StringColumn("scep_endpoint_id")
		TransactionIDColumn       = postgres.StringColumn("transaction_id")
		CsrDigestColumn           = postgres.StringColumn("csr_digest")
		CertificateIDColumn       = postgres.StringColumn("certificate_id")
		MessageTypeColumn         = postgres.StringColumn("message_type")
		StatusColumn              = postgres.StringColumn("status")
		AuthorizationSourceColumn = postgres.StringColumn("authorization_source")
		FailureReasonColumn       = postgres.StringColumn("failure_reason")
		CreatedAtColumn           = postgres.TimestampColumn("created_at")
		UpdatedAtColumn           = postgres.TimestampColumn("updated_at")
		SignerKeyDigestColumn     = postgres.StringColumn("signer_key_digest")
		allColumns                = postgres.ColumnList{IDColumn, OrganizationIDColumn, ScepEndpointIDColumn, TransactionIDColumn, CsrDigestColumn, CertificateIDColumn, MessageTypeColumn, StatusColumn, AuthorizationSourceColumn, FailureReasonColumn, CreatedAtColumn, UpdatedAtColumn, SignerKeyDigestColumn}
		mutableColumns            = postgres.ColumnList{OrganizationIDColumn, ScepEndpointIDColumn, TransactionIDColumn, CsrDigestColumn, CertificateIDColumn, MessageTypeColumn, StatusColumn, AuthorizationSourceColumn, FailureReasonColumn, CreatedAtColumn, UpdatedAtColumn, SignerKeyDigestColumn}
		defaultColumns            = postgres.ColumnList{IDColumn, FailureReasonColumn, CreatedAtColumn, UpdatedAtColumn, SignerKeyDigestColumn}
	)

	return scepTransactionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                  IDColumn,
		OrganizationID:      OrganizationIDColumn,
		ScepEndpointID:      ScepEndpointIDColumn,
		TransactionID:       TransactionIDColumn,
		CsrDigest:           CsrDigestColumn,
		CertificateID:       CertificateIDColumn,
		MessageType:         MessageTypeColumn,
		Status:              StatusColumn,
		AuthorizationSource: AuthorizationSourceColumn,
		FailureReason:       FailureReasonColumn,
		CreatedAt:           CreatedAtColumn,
		UpdatedAt:           UpdatedAtColumn,
		SignerKeyDigest:     SignerKeyDigestColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
