//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScepAuthMethod = newScepAuthMethodTable("public", "scep_auth_method", "")

type scepAuthMethodTable struct {
	postgres.Table

	// Columns
	ID             postgres.ColumnString
	OrganizationID postgres.ColumnString
	ScepEndpointID postgres.ColumnString
	Method         postgres.ColumnString
	Enabled        postgres.ColumnBool
	SecretHash     postgres.ColumnString
	Username       postgres.ColumnString
	PasswordHash   postgres.ColumnString
	ConfiguredAt   postgres.ColumnTimestamp
	CreatedAt      postgres.ColumnTimestamp
	UpdatedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScepAuthMethodTable struct {
	scepAuthMethodTable

	EXCLUDED scepAuthMethodTable
}

// AS creates new ScepAuthMethodTable with assigned alias
func (a ScepAuthMethodTable) AS(alias string) *ScepAuthMethodTable {
	return newScepAuthMethodTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScepAuthMethodTable with assigned schema name
func (a ScepAuthMethodTable) FromSchema(schemaName string) *ScepAuthMethodTable {
	return newScepAuthMethodTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScepAuthMethodTable with assigned table prefix
func (a ScepAuthMethodTable) WithPrefix(prefix string) *ScepAuthMethodTable {
	return newScepAuthMethodTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScepAuthMethodTable with assigned table suffix
func (a ScepAuthMethodTable) WithSuffix(suffix string) *ScepAuthMethodTable {
	return newScepAuthMethodTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScepAuthMethodTable(schemaName, tableName, alias string) *ScepAuthMethodTable {
	return &ScepAuthMethodTable{
		scepAuthMethodTable: newScepAuthMethodTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newScepAuthMethodTableImpl("", "excluded", ""),
	}
}

func newScepAuthMethodTableImpl(schemaName, tableName, alias string) scepAuthMethodTable {
	var (
		IDColumn             = postgres.StringColumn("id")
		OrganizationIDColumn = postgres.StringColumn("organization_id")
		ScepEndpointIDColumn = postgres.StringColumn("scep_endpoint_id")
		MethodColumn         = postgres.StringColumn("method")
		EnabledColumn        = postgres.BoolColumn("enabled")
		SecretHashColumn     = postgres.StringColumn("secret_hash")
		UsernameColumn       = postgres.StringColumn("username")
		PasswordHashColumn   = postgres.StringColumn("password_hash")
		ConfiguredAtColumn   = postgres.TimestampColumn("configured_at")
		CreatedAtColumn      = postgres.TimestampColumn("created_at")
		UpdatedAtColumn      = postgres.TimestampColumn("updated_at")
		allColumns           = postgres.ColumnList{IDColumn, OrganizationIDColumn, ScepEndpointIDColumn, MethodColumn, EnabledColumn, SecretHashColumn, UsernameColumn, PasswordHashColumn, ConfiguredAtColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = postgres.ColumnList{OrganizationIDColumn, ScepEndpointIDColumn, MethodColumn, EnabledColumn, SecretHashColumn, UsernameColumn, PasswordHashColumn, ConfiguredAtColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns       = postgres.ColumnList{IDColumn, EnabledColumn, SecretHashColumn, UsernameColumn, PasswordHashColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return scepAuthMethodTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		OrganizationID: OrganizationIDColumn,
		ScepEndpointID: ScepEndpointIDColumn,
		Method:         MethodColumn,
		Enabled:        EnabledColumn,
		SecretHash:     SecretHashColumn,
		Username:       UsernameColumn,
		PasswordHash:   PasswordHashColumn,
		ConfiguredAt:   ConfiguredAtColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
