//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScepEndpoint = newScepEndpointTable("public", "scep_endpoint", "")

type scepEndpointTable struct {
	postgres.Table

	// Columns
	ID                     postgres.ColumnString
	OrganizationID         postgres.ColumnString
	CertificateAuthorityID postgres.ColumnString
	RaCertificatePem       postgres.ColumnString
	RaPrivateKeyCiphertext postgres.ColumnBytea
	Name                   postgres.ColumnString
	Enabled                postgres.ColumnBool
	ValidityDays           postgres.ColumnInteger
	AllowedEkus            postgres.ColumnString
	SubjectPattern         postgres.ColumnString
	SanPattern             postgres.ColumnString
	AllowLegacyCrypto      postgres.ColumnBool
	RenewalWindowDays      postgres.ColumnInteger
	CreatedAt              postgres.ColumnTimestamp
	UpdatedAt              postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScepEndpointTable struct {
	scepEndpointTable

	EXCLUDED scepEndpointTable
}

// AS creates new ScepEndpointTable with assigned alias
func (a ScepEndpointTable) AS(alias string) *ScepEndpointTable {
	return newScepEndpointTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScepEndpointTable with assigned schema name
func (a ScepEndpointTable) FromSchema(schemaName string) *ScepEndpointTable {
	return newScepEndpointTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScepEndpointTable with assigned table prefix
func (a ScepEndpointTable) WithPrefix(prefix string) *ScepEndpointTable {
	return newScepEndpointTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScepEndpointTable with assigned table suffix
func (a ScepEndpointTable) WithSuffix(suffix string) *ScepEndpointTable {
	return newScepEndpointTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScepEndpointTable(schemaName, tableName, alias string) *ScepEndpointTable {
	return &ScepEndpointTable{
		scepEndpointTable: newScepEndpointTableImpl(schemaName, tableName, alias),
		EXCLUDED:          newScepEndpointTableImpl("", "excluded", ""),
	}
}

func newScepEndpointTableImpl(schemaName, tableName, alias string) scepEndpointTable {
	var (
		IDColumn                     = postgres.StringColumn("id")
		OrganizationIDColumn         = postgres.StringColumn("organization_id")
		CertificateAuthorityIDColumn = postgres.StringColumn("certificate_authority_id")
		RaCertificatePemColumn       = postgres.StringColumn("ra_certificate_pem")
		RaPrivateKeyCiphertextColumn = postgres.ByteaColumn("ra_private_key_ciphertext")
		NameColumn                   = postgres.StringColumn("name")
		EnabledColumn                = postgres.BoolColumn("enabled")
		ValidityDaysColumn           = postgres.IntegerColumn("validity_days")
		AllowedEkusColumn            = postgres.StringColumn("allowed_ekus")
		SubjectPatternColumn         = postgres.StringColumn("subject_pattern")
		SanPatternColumn             = postgres.StringColumn("san_pattern")
		AllowLegacyCryptoColumn      = postgres.BoolColumn("allow_legacy_crypto")
		RenewalWindowDaysColumn      = postgres.IntegerColumn("renewal_window_days")
		CreatedAtColumn              = postgres.TimestampColumn("created_at")
		UpdatedAtColumn              = postgres.TimestampColumn("updated_at")
		allColumns                   = postgres.ColumnList{IDColumn, OrganizationIDColumn, CertificateAuthorityIDColumn, RaCertificatePemColumn, RaPrivateKeyCiphertextColumn, NameColumn, EnabledColumn, ValidityDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, AllowLegacyCryptoColumn, RenewalWindowDaysColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns               = postgres.ColumnList{OrganizationIDColumn, CertificateAuthorityIDColumn, RaCertificatePemColumn, RaPrivateKeyCiphertextColumn, NameColumn, EnabledColumn, ValidityDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, AllowLegacyCryptoColumn, RenewalWindowDaysColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns               = postgres.ColumnList{IDColumn, EnabledColumn, ValidityDaysColumn, AllowedEkusColumn, SubjectPatternColumn, SanPatternColumn, AllowLegacyCryptoColumn, RenewalWindowDaysColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return scepEndpointTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                     IDColumn,
		OrganizationID:         OrganizationIDColumn,
		CertificateAuthorityID: CertificateAuthorityIDColumn,
		RaCertificatePem:       RaCertificatePemColumn,
		RaPrivateKeyCiphertext: RaPrivateKeyCiphertextColumn,
		Name:                   NameColumn,
		Enabled:                EnabledColumn,
		ValidityDays:           ValidityDaysColumn,
		AllowedEkus:            AllowedEkusColumn,
		SubjectPattern:         SubjectPatternColumn,
		SanPattern:             SanPatternColumn,
		AllowLegacyCrypto:      AllowLegacyCryptoColumn,
		RenewalWindowDays:      RenewalWindowDaysColumn,
		CreatedAt:              CreatedAtColumn,
		UpdatedAt:              UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
