//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ScepChallenge = newScepChallengeTable("public", "scep_challenge", "")

type scepChallengeTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	OrganizationID  postgres.ColumnString
	ScepEndpointID  postgres.ColumnString
	LookupDigest    postgres.ColumnBytea
	SecretHash      postgres.ColumnString
	ExpectedSubject postgres.ColumnString
	ExpectedSans    postgres.ColumnString
	ExternalID      postgres.ColumnString
	ExpiresAt       postgres.ColumnTimestamp
	UsedAt          postgres.ColumnTimestamp
	CreatedAt       postgres.ColumnTimestamp
	ExpectedEkus    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ScepChallengeTable struct {
	scepChallengeTable

	EXCLUDED scepChallengeTable
}

// AS creates new ScepChallengeTable with assigned alias
func (a ScepChallengeTable) AS(alias string) *ScepChallengeTable {
	return newScepChallengeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ScepChallengeTable with assigned schema name
func (a ScepChallengeTable) FromSchema(schemaName string) *ScepChallengeTable {
	return newScepChallengeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ScepChallengeTable with assigned table prefix
func (a ScepChallengeTable) WithPrefix(prefix string) *ScepChallengeTable {
	return newScepChallengeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ScepChallengeTable with assigned table suffix
func (a ScepChallengeTable) WithSuffix(suffix string) *ScepChallengeTable {
	return newScepChallengeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newScepChallengeTable(schemaName, tableName, alias string) *ScepChallengeTable {
	return &ScepChallengeTable{
		scepChallengeTable: newScepChallengeTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newScepChallengeTableImpl("", "excluded", ""),
	}
}

func newScepChallengeTableImpl(schemaName, tableName, alias string) scepChallengeTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		OrganizationIDColumn  = postgres.StringColumn("organization_id")
		ScepEndpointIDColumn  = postgres.StringColumn("scep_endpoint_id")
		LookupDigestColumn    = postgres.ByteaColumn("lookup_digest")
		SecretHashColumn      = postgres.StringColumn("secret_hash")
		ExpectedSubjectColumn = postgres.StringColumn("expected_subject")
		ExpectedSansColumn    = postgres.StringColumn("expected_sans")
		ExternalIDColumn      = postgres.StringColumn("external_id")
		ExpiresAtColumn       = postgres.TimestampColumn("expires_at")
		UsedAtColumn          = postgres.TimestampColumn("used_at")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		ExpectedEkusColumn    = postgres.StringColumn("expected_ekus")
		allColumns            = postgres.ColumnList{IDColumn, OrganizationIDColumn, ScepEndpointIDColumn, LookupDigestColumn, SecretHashColumn, ExpectedSubjectColumn, ExpectedSansColumn, ExternalIDColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn, ExpectedEkusColumn}
		mutableColumns        = postgres.ColumnList{OrganizationIDColumn, ScepEndpointIDColumn, LookupDigestColumn, SecretHashColumn, ExpectedSubjectColumn, ExpectedSansColumn, ExternalIDColumn, ExpiresAtColumn, UsedAtColumn, CreatedAtColumn, ExpectedEkusColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, ExpectedSubjectColumn, ExpectedSansColumn, ExternalIDColumn, CreatedAtColumn, ExpectedEkusColumn}
	)

	return scepChallengeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		OrganizationID:  OrganizationIDColumn,
		ScepEndpointID:  ScepEndpointIDColumn,
		LookupDigest:    LookupDigestColumn,
		SecretHash:      SecretHashColumn,
		ExpectedSubject: ExpectedSubjectColumn,
		ExpectedSans:    ExpectedSansColumn,
		ExternalID:      ExternalIDColumn,
		ExpiresAt:       ExpiresAtColumn,
		UsedAt:          UsedAtColumn,
		CreatedAt:       CreatedAtColumn,
		ExpectedEkus:    ExpectedEkusColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
