//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Session = newSessionTable("public", "session", "")

type sessionTable struct {
	postgres.Table

	// Columns
	ID                postgres.ColumnString
	UserID            postgres.ColumnString
	OrganizationID    postgres.ColumnString
	ExpiresAt         postgres.ColumnTimestamp
	CreatedAt         postgres.ColumnTimestamp
	SteppedUpAt       postgres.ColumnTimestampz
	WebauthnSession   postgres.ColumnString
	PendingTotpSecret postgres.ColumnBytea
	PendingTotpLabel  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type SessionTable struct {
	sessionTable

	EXCLUDED sessionTable
}

// AS creates new SessionTable with assigned alias
func (a SessionTable) AS(alias string) *SessionTable {
	return newSessionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SessionTable with assigned schema name
func (a SessionTable) FromSchema(schemaName string) *SessionTable {
	return newSessionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SessionTable with assigned table prefix
func (a SessionTable) WithPrefix(prefix string) *SessionTable {
	return newSessionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SessionTable with assigned table suffix
func (a SessionTable) WithSuffix(suffix string) *SessionTable {
	return newSessionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSessionTable(schemaName, tableName, alias string) *SessionTable {
	return &SessionTable{
		sessionTable: newSessionTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newSessionTableImpl("", "excluded", ""),
	}
}

func newSessionTableImpl(schemaName, tableName, alias string) sessionTable {
	var (
		IDColumn                = postgres.StringColumn("id")
		UserIDColumn            = postgres.StringColumn("user_id")
		OrganizationIDColumn    = postgres.StringColumn("organization_id")
		ExpiresAtColumn         = postgres.TimestampColumn("expires_at")
		CreatedAtColumn         = postgres.TimestampColumn("created_at")
		SteppedUpAtColumn       = postgres.TimestampzColumn("stepped_up_at")
		WebauthnSessionColumn   = postgres.StringColumn("webauthn_session")
		PendingTotpSecretColumn = postgres.ByteaColumn("pending_totp_secret")
		PendingTotpLabelColumn  = postgres.StringColumn("pending_totp_label")
		allColumns              = postgres.ColumnList{IDColumn, UserIDColumn, OrganizationIDColumn, ExpiresAtColumn, CreatedAtColumn, SteppedUpAtColumn, WebauthnSessionColumn, PendingTotpSecretColumn, PendingTotpLabelColumn}
		mutableColumns          = postgres.ColumnList{UserIDColumn, OrganizationIDColumn, ExpiresAtColumn, CreatedAtColumn, SteppedUpAtColumn, WebauthnSessionColumn, PendingTotpSecretColumn, PendingTotpLabelColumn}
		defaultColumns          = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return sessionTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                IDColumn,
		UserID:            UserIDColumn,
		OrganizationID:    OrganizationIDColumn,
		ExpiresAt:         ExpiresAtColumn,
		CreatedAt:         CreatedAtColumn,
		SteppedUpAt:       SteppedUpAtColumn,
		WebauthnSession:   WebauthnSessionColumn,
		PendingTotpSecret: PendingTotpSecretColumn,
		PendingTotpLabel:  PendingTotpLabelColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
