//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	AcmeAccount = AcmeAccount.FromSchema(schema)
	AcmeAuthorization = AcmeAuthorization.FromSchema(schema)
	AcmeChallenge = AcmeChallenge.FromSchema(schema)
	AcmeEabCredential = AcmeEabCredential.FromSchema(schema)
	AcmeEndpoint = AcmeEndpoint.FromSchema(schema)
	AcmeNonce = AcmeNonce.FromSchema(schema)
	AcmeOrder = AcmeOrder.FromSchema(schema)
	AuditEvent = AuditEvent.FromSchema(schema)
	CaImportJob = CaImportJob.FromSchema(schema)
	Certificate = Certificate.FromSchema(schema)
	CertificateAuthority = CertificateAuthority.FromSchema(schema)
	CertificateRevocation = CertificateRevocation.FromSchema(schema)
	CertificateSigningAudit = CertificateSigningAudit.FromSchema(schema)
	CrlPublication = CrlPublication.FromSchema(schema)
	EmailInvitation = EmailInvitation.FromSchema(schema)
	EstCredential = EstCredential.FromSchema(schema)
	EstEndpoint = EstEndpoint.FromSchema(schema)
	EstEnrollment = EstEnrollment.FromSchema(schema)
	LoginChallenge = LoginChallenge.FromSchema(schema)
	MagicLink = MagicLink.FromSchema(schema)
	Migrations = Migrations.FromSchema(schema)
	OcspResponseCache = OcspResponseCache.FromSchema(schema)
	Organization = Organization.FromSchema(schema)
	ScepAuthMethod = ScepAuthMethod.FromSchema(schema)
	ScepChallenge = ScepChallenge.FromSchema(schema)
	ScepEndpoint = ScepEndpoint.FromSchema(schema)
	ScepIntuneConnection = ScepIntuneConnection.FromSchema(schema)
	ScepTransaction = ScepTransaction.FromSchema(schema)
	Session = Session.FromSchema(schema)
	User = User.FromSchema(schema)
	UserRecoveryCode = UserRecoveryCode.FromSchema(schema)
	UserTotpCredential = UserTotpCredential.FromSchema(schema)
	UserWebauthnCredential = UserWebauthnCredential.FromSchema(schema)
}
