//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserWebauthnCredential = newUserWebauthnCredentialTable("public", "user_webauthn_credential", "")

type userWebauthnCredentialTable struct {
	postgres.Table

	// Columns
	ID              postgres.ColumnString
	UserID          postgres.ColumnString
	CredentialID    postgres.ColumnBytea
	PublicKey       postgres.ColumnBytea
	AttestationType postgres.ColumnString
	Aaguid          postgres.ColumnBytea
	Transports      postgres.ColumnString
	SignCount       postgres.ColumnInteger
	BackupEligible  postgres.ColumnBool
	BackupState     postgres.ColumnBool
	CloneWarning    postgres.ColumnBool
	Label           postgres.ColumnString
	CreatedAt       postgres.ColumnTimestamp
	LastUsedAt      postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserWebauthnCredentialTable struct {
	userWebauthnCredentialTable

	EXCLUDED userWebauthnCredentialTable
}

// AS creates new UserWebauthnCredentialTable with assigned alias
func (a UserWebauthnCredentialTable) AS(alias string) *UserWebauthnCredentialTable {
	return newUserWebauthnCredentialTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserWebauthnCredentialTable with assigned schema name
func (a UserWebauthnCredentialTable) FromSchema(schemaName string) *UserWebauthnCredentialTable {
	return newUserWebauthnCredentialTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserWebauthnCredentialTable with assigned table prefix
func (a UserWebauthnCredentialTable) WithPrefix(prefix string) *UserWebauthnCredentialTable {
	return newUserWebauthnCredentialTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserWebauthnCredentialTable with assigned table suffix
func (a UserWebauthnCredentialTable) WithSuffix(suffix string) *UserWebauthnCredentialTable {
	return newUserWebauthnCredentialTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserWebauthnCredentialTable(schemaName, tableName, alias string) *UserWebauthnCredentialTable {
	return &UserWebauthnCredentialTable{
		userWebauthnCredentialTable: newUserWebauthnCredentialTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newUserWebauthnCredentialTableImpl("", "excluded", ""),
	}
}

func newUserWebauthnCredentialTableImpl(schemaName, tableName, alias string) userWebauthnCredentialTable {
	var (
		IDColumn              = postgres.StringColumn("id")
		UserIDColumn          = postgres.StringColumn("user_id")
		CredentialIDColumn    = postgres.ByteaColumn("credential_id")
		PublicKeyColumn       = postgres.ByteaColumn("public_key")
		AttestationTypeColumn = postgres.StringColumn("attestation_type")
		AaguidColumn          = postgres.ByteaColumn("aaguid")
		TransportsColumn      = postgres.StringColumn("transports")
		SignCountColumn       = postgres.IntegerColumn("sign_count")
		BackupEligibleColumn  = postgres.BoolColumn("backup_eligible")
		BackupStateColumn     = postgres.BoolColumn("backup_state")
		CloneWarningColumn    = postgres.BoolColumn("clone_warning")
		LabelColumn           = postgres.StringColumn("label")
		CreatedAtColumn       = postgres.TimestampColumn("created_at")
		LastUsedAtColumn      = postgres.TimestampColumn("last_used_at")
		allColumns            = postgres.ColumnList{IDColumn, UserIDColumn, CredentialIDColumn, PublicKeyColumn, AttestationTypeColumn, AaguidColumn, TransportsColumn, SignCountColumn, BackupEligibleColumn, BackupStateColumn, CloneWarningColumn, LabelColumn, CreatedAtColumn, LastUsedAtColumn}
		mutableColumns        = postgres.ColumnList{UserIDColumn, CredentialIDColumn, PublicKeyColumn, AttestationTypeColumn, AaguidColumn, TransportsColumn, SignCountColumn, BackupEligibleColumn, BackupStateColumn, CloneWarningColumn, LabelColumn, CreatedAtColumn, LastUsedAtColumn}
		defaultColumns        = postgres.ColumnList{IDColumn, AttestationTypeColumn, AaguidColumn, TransportsColumn, SignCountColumn, BackupEligibleColumn, BackupStateColumn, CloneWarningColumn, LabelColumn, CreatedAtColumn}
	)

	return userWebauthnCredentialTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		UserID:          UserIDColumn,
		CredentialID:    CredentialIDColumn,
		PublicKey:       PublicKeyColumn,
		AttestationType: AttestationTypeColumn,
		Aaguid:          AaguidColumn,
		Transports:      TransportsColumn,
		SignCount:       SignCountColumn,
		BackupEligible:  BackupEligibleColumn,
		BackupState:     BackupStateColumn,
		CloneWarning:    CloneWarningColumn,
		Label:           LabelColumn,
		CreatedAt:       CreatedAtColumn,
		LastUsedAt:      LastUsedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
