//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserRecoveryCode = newUserRecoveryCodeTable("public", "user_recovery_code", "")

type userRecoveryCodeTable struct {
	postgres.Table

	// Columns
	ID           postgres.ColumnString
	UserID       postgres.ColumnString
	Selector     postgres.ColumnString
	VerifierHash postgres.ColumnString
	UsedAt       postgres.ColumnTimestamp
	CreatedAt    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserRecoveryCodeTable struct {
	userRecoveryCodeTable

	EXCLUDED userRecoveryCodeTable
}

// AS creates new UserRecoveryCodeTable with assigned alias
func (a UserRecoveryCodeTable) AS(alias string) *UserRecoveryCodeTable {
	return newUserRecoveryCodeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserRecoveryCodeTable with assigned schema name
func (a UserRecoveryCodeTable) FromSchema(schemaName string) *UserRecoveryCodeTable {
	return newUserRecoveryCodeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserRecoveryCodeTable with assigned table prefix
func (a UserRecoveryCodeTable) WithPrefix(prefix string) *UserRecoveryCodeTable {
	return newUserRecoveryCodeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserRecoveryCodeTable with assigned table suffix
func (a UserRecoveryCodeTable) WithSuffix(suffix string) *UserRecoveryCodeTable {
	return newUserRecoveryCodeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserRecoveryCodeTable(schemaName, tableName, alias string) *UserRecoveryCodeTable {
	return &UserRecoveryCodeTable{
		userRecoveryCodeTable: newUserRecoveryCodeTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newUserRecoveryCodeTableImpl("", "excluded", ""),
	}
}

func newUserRecoveryCodeTableImpl(schemaName, tableName, alias string) userRecoveryCodeTable {
	var (
		IDColumn           = postgres.StringColumn("id")
		UserIDColumn       = postgres.StringColumn("user_id")
		SelectorColumn     = postgres.StringColumn("selector")
		VerifierHashColumn = postgres.StringColumn("verifier_hash")
		UsedAtColumn       = postgres.TimestampColumn("used_at")
		CreatedAtColumn    = postgres.TimestampColumn("created_at")
		allColumns         = postgres.ColumnList{IDColumn, UserIDColumn, SelectorColumn, VerifierHashColumn, UsedAtColumn, CreatedAtColumn}
		mutableColumns     = postgres.ColumnList{UserIDColumn, SelectorColumn, VerifierHashColumn, UsedAtColumn, CreatedAtColumn}
		defaultColumns     = postgres.ColumnList{IDColumn, CreatedAtColumn}
	)

	return userRecoveryCodeTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		UserID:       UserIDColumn,
		Selector:     SelectorColumn,
		VerifierHash: VerifierHashColumn,
		UsedAt:       UsedAtColumn,
		CreatedAt:    CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
