//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var UserTotpCredential = newUserTotpCredentialTable("public", "user_totp_credential", "")

type userTotpCredentialTable struct {
	postgres.Table

	// Columns
	UserID      postgres.ColumnString
	Secret      postgres.ColumnBytea
	LastStep    postgres.ColumnInteger
	ConfirmedAt postgres.ColumnTimestamp
	LastUsedAt  postgres.ColumnTimestamp
	ID          postgres.ColumnString
	Label       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type UserTotpCredentialTable struct {
	userTotpCredentialTable

	EXCLUDED userTotpCredentialTable
}

// AS creates new UserTotpCredentialTable with assigned alias
func (a UserTotpCredentialTable) AS(alias string) *UserTotpCredentialTable {
	return newUserTotpCredentialTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UserTotpCredentialTable with assigned schema name
func (a UserTotpCredentialTable) FromSchema(schemaName string) *UserTotpCredentialTable {
	return newUserTotpCredentialTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UserTotpCredentialTable with assigned table prefix
func (a UserTotpCredentialTable) WithPrefix(prefix string) *UserTotpCredentialTable {
	return newUserTotpCredentialTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UserTotpCredentialTable with assigned table suffix
func (a UserTotpCredentialTable) WithSuffix(suffix string) *UserTotpCredentialTable {
	return newUserTotpCredentialTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUserTotpCredentialTable(schemaName, tableName, alias string) *UserTotpCredentialTable {
	return &UserTotpCredentialTable{
		userTotpCredentialTable: newUserTotpCredentialTableImpl(schemaName, tableName, alias),
		EXCLUDED:                newUserTotpCredentialTableImpl("", "excluded", ""),
	}
}

func newUserTotpCredentialTableImpl(schemaName, tableName, alias string) userTotpCredentialTable {
	var (
		UserIDColumn      = postgres.StringColumn("user_id")
		SecretColumn      = postgres.ByteaColumn("secret")
		LastStepColumn    = postgres.IntegerColumn("last_step")
		ConfirmedAtColumn = postgres.TimestampColumn("confirmed_at")
		LastUsedAtColumn  = postgres.TimestampColumn("last_used_at")
		IDColumn          = postgres.StringColumn("id")
		LabelColumn       = postgres.StringColumn("label")
		allColumns        = postgres.ColumnList{UserIDColumn, SecretColumn, LastStepColumn, ConfirmedAtColumn, LastUsedAtColumn, IDColumn, LabelColumn}
		mutableColumns    = postgres.ColumnList{UserIDColumn, SecretColumn, LastStepColumn, ConfirmedAtColumn, LastUsedAtColumn, LabelColumn}
		defaultColumns    = postgres.ColumnList{LastStepColumn, ConfirmedAtColumn, IDColumn, LabelColumn}
	)

	return userTotpCredentialTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:      UserIDColumn,
		Secret:      SecretColumn,
		LastStep:    LastStepColumn,
		ConfirmedAt: ConfirmedAtColumn,
		LastUsedAt:  LastUsedAtColumn,
		ID:          IDColumn,
		Label:       LabelColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
