//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AcmeAuthorization struct {
	ID              uuid.UUID `sql:"primary_key"`
	OrganizationID  uuid.UUID
	AcmeOrderID     uuid.UUID
	IdentifierType  string
	IdentifierValue string
	Status          string
	ExpiresAt       time.Time
	ValidatedAt     *time.Time
	CreatedAt       time.Time
}
