//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AcmeAccount struct {
	ID              uuid.UUID `sql:"primary_key"`
	OrganizationID  uuid.UUID
	AcmeEndpointID  uuid.UUID
	JwkThumbprint   string
	JwkJSON         string
	Status          string
	Contact         string
	EabCredentialID *uuid.UUID
	IdentifierPin   string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
