//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AcmeEabCredential struct {
	ID               uuid.UUID `sql:"primary_key"`
	OrganizationID   uuid.UUID
	AcmeEndpointID   uuid.UUID
	Label            string
	Kid              string
	MacKeyCiphertext []byte
	IdentifierPin    string
	SingleUse        bool
	ExpiresAt        *time.Time
	UsedAt           *time.Time
	RevokedAt        *time.Time
	CreatedAt        time.Time
}
