//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AcmeOrder struct {
	ID             uuid.UUID `sql:"primary_key"`
	OrganizationID uuid.UUID
	AcmeEndpointID uuid.UUID
	AcmeAccountID  uuid.UUID
	Status         string
	ExpiresAt      time.Time
	NotBefore      *time.Time
	NotAfter       *time.Time
	CertificateID  *uuid.UUID
	ErrorType      string
	ErrorDetail    string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
