//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type AuditEvent struct {
	ID             uuid.UUID `sql:"primary_key"`
	OrganizationID uuid.UUID
	ActorUserID    *uuid.UUID
	ActorEmail     string
	Action         string
	Target         string
	Detail         string
	CreatedAt      time.Time
	ActorIP        string
	ActorUserAgent string
	ActorSessionID string
}
