//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type CaImportJob struct {
	ID                     uuid.UUID `sql:"primary_key"`
	OrganizationID         uuid.UUID
	CreatedBy              *uuid.UUID
	CaName                 string
	CaType                 string
	Algorithm              string
	CertificatePem         string
	ChainPem               string
	KmsImportJob           string
	KmsCryptoKey           string
	KmsKeyVersion          string
	WrappingMethod         string
	WrappingPublicKeyPem   string
	State                  string
	FailureReason          string
	CertificateAuthorityID *uuid.UUID
	ExpiresAt              *time.Time
	CreatedAt              time.Time
	CancelledBy            *uuid.UUID
}
