//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type CertificateAuthority struct {
	ID             uuid.UUID `sql:"primary_key"`
	OrganizationID uuid.UUID
	ParentID       *uuid.UUID
	Name           string
	Type           string
	Status         string
	Subject        string
	Algorithm      string
	KmsKeyVersion  string
	CertificatePem string
	ChainPem       string
	ExportPosture  string
	NotBefore      time.Time
	NotAfter       time.Time
	IssuedCount    int64
	LastSignedAt   *time.Time
	CreatedAt      time.Time
	IssuanceEkus   string
	DeletedAt      *time.Time
}
