//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type CertificateSigningAudit struct {
	ID                     uuid.UUID `sql:"primary_key"`
	OrganizationID         uuid.UUID
	CertificateAuthorityID uuid.UUID
	RequesterUserID        *uuid.UUID
	KmsKeyVersion          string
	CsrDigest              string
	CertificateSerial      string
	Purpose                string
	SignedAt               time.Time
}
