//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Certificate struct {
	ID                     uuid.UUID `sql:"primary_key"`
	OrganizationID         uuid.UUID
	CertificateAuthorityID uuid.UUID
	Serial                 string
	Subject                string
	Sans                   string
	Status                 string
	CsrDigest              string
	CertificatePem         string
	ChainPem               string
	IssuedAt               time.Time
	RevokedAt              *time.Time
	ExpiresAt              time.Time
	Profile                string
	Ekus                   string
	ExpiryNotifiedAt       *time.Time
}
