//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type CrlPublication struct {
	OrganizationID         uuid.UUID
	CertificateAuthorityID uuid.UUID `sql:"primary_key"`
	CrlDer                 []byte
	CrlNumber              int64
	ThisUpdate             *time.Time
	NextUpdate             *time.Time
	PublishedAt            *time.Time
	LastAttemptAt          *time.Time
	LastError              string
}
