//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type EmailInvitation struct {
	ID             uuid.UUID `sql:"primary_key"`
	OrganizationID uuid.UUID
	Email          string
	Role           string
	ExpiresAt      time.Time
	AcceptedAt     *time.Time
	CreatedAt      time.Time
	TokenHash      string
	Name           *string
}
