//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type EstEnrollment struct {
	ID              uuid.UUID `sql:"primary_key"`
	OrganizationID  uuid.UUID
	EstEndpointID   uuid.UUID
	EstCredentialID *uuid.UUID
	CertificateID   *uuid.UUID
	Subject         string
	Operation       string
	CreatedAt       time.Time
	Status          string
	FailureReason   string
}
