//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type EstCredential struct {
	ID             uuid.UUID `sql:"primary_key"`
	OrganizationID uuid.UUID
	EstEndpointID  uuid.UUID
	Label          string
	Username       string
	SecretHash     string
	IdentifierPin  string
	ExpiresAt      *time.Time
	UsedAt         *time.Time
	RevokedAt      *time.Time
	CreatedAt      time.Time
}
