//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type OcspResponseCache struct {
	OrganizationID         uuid.UUID
	CertificateAuthorityID uuid.UUID `sql:"primary_key"`
	Serial                 string    `sql:"primary_key"`
	HashAlgorithm          int32     `sql:"primary_key"`
	CertificateStatus      string
	ResponseDer            []byte
	ThisUpdate             time.Time
	NextUpdate             time.Time
}
