//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ScepTransaction struct {
	ID                  uuid.UUID `sql:"primary_key"`
	OrganizationID      uuid.UUID
	ScepEndpointID      uuid.UUID
	TransactionID       string
	CsrDigest           string
	CertificateID       *uuid.UUID
	MessageType         string
	Status              string
	AuthorizationSource string
	FailureReason       string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	SignerKeyDigest     string
}
