//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ScepEndpoint struct {
	ID                     uuid.UUID `sql:"primary_key"`
	OrganizationID         uuid.UUID
	CertificateAuthorityID uuid.UUID
	RaCertificatePem       string
	RaPrivateKeyCiphertext []byte
	Name                   string
	Enabled                bool
	ValidityDays           int32
	AllowedEkus            string
	SubjectPattern         string
	SanPattern             string
	AllowLegacyCrypto      bool
	RenewalWindowDays      int32
	CreatedAt              time.Time
	UpdatedAt              time.Time
}
