//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type ScepChallenge struct {
	ID              uuid.UUID `sql:"primary_key"`
	OrganizationID  uuid.UUID
	ScepEndpointID  uuid.UUID
	LookupDigest    []byte
	SecretHash      string
	ExpectedSubject string
	ExpectedSans    string
	ExternalID      string
	ExpiresAt       time.Time
	UsedAt          *time.Time
	CreatedAt       time.Time
	ExpectedEkus    string
}
