//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Session struct {
	ID                uuid.UUID `sql:"primary_key"`
	UserID            uuid.UUID
	OrganizationID    *uuid.UUID
	ExpiresAt         time.Time
	CreatedAt         time.Time
	SteppedUpAt       *time.Time
	WebauthnSession   *string
	PendingTotpSecret *[]byte
	PendingTotpLabel  *string
}
