//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserWebauthnCredential struct {
	ID              uuid.UUID `sql:"primary_key"`
	UserID          uuid.UUID
	CredentialID    []byte
	PublicKey       []byte
	AttestationType string
	Aaguid          []byte
	Transports      string
	SignCount       int64
	BackupEligible  bool
	BackupState     bool
	CloneWarning    bool
	Label           string
	CreatedAt       time.Time
	LastUsedAt      *time.Time
}
