//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type UserTotpCredential struct {
	UserID      uuid.UUID
	Secret      []byte
	LastStep    int64
	ConfirmedAt time.Time
	LastUsedAt  *time.Time
	ID          uuid.UUID `sql:"primary_key"`
	Label       string
}
